// Glossary — Accounting & finance. [term, bangla term, english definition, bangla definition, optional link]
module.exports = {
  id: "accounting", en: "Accounting & finance", bn: "হিসাব ও অর্থ",
  terms: [
    ["Chart of accounts (CoA)", "হিসাবের তালিকা", "The structured list of all ledger accounts a company uses.", "কোম্পানি যত লেজার হিসাব ব্যবহার করে, তার সাজানো তালিকা।", "/lab/0014-odoo-accounting-setup-bangladesh"],
    ["General ledger (GL)", "সাধারণ খতিয়ান", "The complete record of all accounting entries, by account.", "হিসাব অনুযায়ী সব হিসাব-এন্ট্রির পূর্ণ রেকর্ড।"],
    ["Journal", "জার্নাল", "A book where entries of one type are recorded, such as sales, purchases, bank or cash.", "এক ধরনের এন্ট্রি যে খাতায় লেখা হয়, যেমন বিক্রি, কেনা, ব্যাংক বা নগদ।"],
    ["Journal entry", "জার্নাল এন্ট্রি", "A balanced accounting record of debits and credits.", "ডেবিট আর ক্রেডিটের ভারসাম্যপূর্ণ হিসাব-রেকর্ড।"],
    ["Debit / Credit", "ডেবিট / ক্রেডিট", "The two sides of every double-entry transaction.", "দুতরফা দাখিলার প্রতিটি লেনদেনের দুই দিক।"],
    ["Double-entry bookkeeping", "দুতরফা দাখিলা পদ্ধতি", "Every transaction is recorded in at least two accounts with equal debits and credits.", "প্রতিটি লেনদেন অন্তত দুটি হিসাবে লেখা হয়, ডেবিট আর ক্রেডিট সমান রেখে।"],
    ["Trial balance", "রেওয়ামিল", "A list of all account balances, used to check that debits equal credits.", "সব হিসাবের ব্যালেন্সের তালিকা, ডেবিট আর ক্রেডিট সমান কি না যাচাই করতে।"],
    ["Balance sheet", "স্থিতিপত্র", "A statement of assets, liabilities and equity at a point in time.", "নির্দিষ্ট তারিখে সম্পদ, দায় আর মালিকানাস্বত্বের বিবরণী।"],
    ["Profit & loss (P&L)", "লাভ-ক্ষতি বিবরণী", "A statement of income and expenses over a period.", "নির্দিষ্ট সময়ের আয় আর ব্যয়ের বিবরণী।"],
    ["Cash flow statement", "নগদ প্রবাহ বিবরণী", "A statement showing cash coming in and going out from operations, investing and financing.", "পরিচালনা, বিনিয়োগ আর অর্থায়ন থেকে নগদ আসা-যাওয়ার বিবরণী।"],
    ["Accounts receivable (AR)", "প্রাপ্য হিসাব", "Money customers owe the company.", "কাস্টমারদের কাছে কোম্পানির পাওনা টাকা।"],
    ["Accounts payable (AP)", "প্রদেয় হিসাব", "Money the company owes suppliers.", "সরবরাহকারীদের কাছে কোম্পানির দেনা।"],
    ["DSO (Days Sales Outstanding)", "গড় আদায়ের দিন", "The average number of days it takes to collect payment after a sale.", "বিক্রির পর টাকা আদায় হতে গড়ে কত দিন লাগে।", "/tools/odoo-roi-calculator/"],
    ["Ageing report", "বকেয়ার বয়স-ভিত্তিক রিপোর্ট", "Receivables or payables grouped by how overdue they are.", "কতদিন ধরে বকেয়া, সে অনুযায়ী সাজানো প্রাপ্য বা প্রদেয়।"],
    ["Credit limit", "ক্রেডিট লিমিট", "The maximum amount a customer may owe before new orders are blocked.", "নতুন অর্ডার আটকে দেওয়ার আগে একজন কাস্টমার সর্বোচ্চ কত বাকি রাখতে পারবেন।"],
    ["Payment terms", "পেমেন্টের শর্ত", "When an invoice must be paid, for example 30 days or 50% advance.", "ইনভয়েস কবে পরিশোধ করতে হবে, যেমন ৩০ দিনে বা ৫০% অগ্রিম।"],
    ["Invoice", "ইনভয়েস / চালান", "A request for payment for goods or services supplied.", "সরবরাহ করা পণ্য বা সেবার জন্য পেমেন্টের দাবি।"],
    ["Vendor bill", "ভেন্ডর বিল", "A supplier's invoice recorded as a payable.", "সরবরাহকারীর ইনভয়েস, যা প্রদেয় হিসেবে রেকর্ড হয়।"],
    ["Credit note", "ক্রেডিট নোট", "A document reducing an invoice amount, for returns or discounts.", "ফেরত বা ছাড়ের জন্য ইনভয়েসের অঙ্ক কমানোর ডকুমেন্ট।", "/tools/vat-mushak-helper/"],
    ["Debit note", "ডেবিট নোট", "A document increasing an amount owed, or reducing a supplier bill.", "দেনার অঙ্ক বাড়ানো বা সরবরাহকারীর বিল কমানোর ডকুমেন্ট।"],
    ["Bank reconciliation", "ব্যাংক মিলকরণ", "Matching bank statement lines with accounting entries.", "ব্যাংক স্টেটমেন্টের লাইন হিসাবের এন্ট্রির সঙ্গে মেলানো।"],
    ["Month-end close", "মাস-শেষের ক্লোজিং", "The process of finalising a month's books: accruals, reconciliations and reports.", "এক মাসের হিসাব চূড়ান্ত করার প্রক্রিয়া: অ্যাক্রুয়াল, মিলকরণ আর রিপোর্ট।"],
    ["Lock date", "লক ডেট", "A date before which posted entries can't be changed.", "যে তারিখের আগের পোস্ট করা এন্ট্রি আর বদলানো যায় না।"],
    ["Fiscal year", "অর্থবছর", "The 12-month accounting year. In Bangladesh it usually runs July to June.", "হিসাবের ১২ মাসের বছর। বাংলাদেশে সাধারণত জুলাই থেকে জুন।"],
    ["Accrual", "অ্যাক্রুয়াল (উপার্জিত হিসাব)", "Recording income or expense when it is earned or incurred, not when cash moves.", "টাকা আসা-যাওয়ার সময় নয়, আয় বা ব্যয় যখন হয় তখনই রেকর্ড করা।"],
    ["Prepayment", "অগ্রিম পরিশোধ", "Payment made before goods or services are received.", "পণ্য বা সেবা পাওয়ার আগে করা পেমেন্ট।"],
    ["Depreciation", "অবচয়", "Spreading the cost of a fixed asset over its useful life.", "স্থায়ী সম্পদের খরচ তার ব্যবহারযোগ্য জীবনকাল জুড়ে ভাগ করা।"],
    ["Fixed asset", "স্থায়ী সম্পদ", "A long-term asset such as machinery, buildings or vehicles.", "দীর্ঘমেয়াদি সম্পদ, যেমন যন্ত্রপাতি, ভবন বা গাড়ি।"],
    ["Asset register", "সম্পদ রেজিস্টার", "The list of fixed assets with cost, location and depreciation.", "খরচ, অবস্থান আর অবচয়সহ স্থায়ী সম্পদের তালিকা।"],
    ["Cost centre", "কস্ট সেন্টার", "A department or unit whose costs are tracked separately.", "যে বিভাগ বা ইউনিটের খরচ আলাদাভাবে ট্র্যাক হয়।"],
    ["Analytic account", "অ্যানালিটিক অ্যাকাউন্ট", "Odoo's way of tracking costs and revenue by project, department or unit.", "প্রজেক্ট, বিভাগ বা ইউনিট অনুযায়ী খরচ আর আয় ট্র্যাক করার Odoo-র পদ্ধতি।"],
    ["Budget", "বাজেট", "Planned income and expenses to compare with actuals.", "প্রকৃত হিসাবের সঙ্গে তুলনার জন্য পরিকল্পিত আয় আর ব্যয়।"],
    ["Variance", "ব্যবধান (ভেরিয়েন্স)", "The difference between budgeted or standard and actual figures.", "বাজেট বা মানক অঙ্ক আর প্রকৃত অঙ্কের পার্থক্য।"],
    ["Working capital", "চলতি মূলধন", "Current assets minus current liabilities: the money tied up in running the business.", "চলতি সম্পদ বিয়োগ চলতি দায়: ব্যবসা চালাতে যে টাকা আটকে থাকে।", "/tools/odoo-roi-calculator/"],
    ["Cost of capital", "মূলধনের খরচ", "The interest rate the business pays, or could earn, on money.", "টাকার ওপর ব্যবসা যে সুদ দেয় বা পেতে পারত।"],
    ["Gross margin", "মোট মার্জিন", "Sales minus cost of goods sold, as a percentage of sales.", "বিক্রি বিয়োগ বিক্রীত পণ্যের খরচ, বিক্রির শতাংশ হিসেবে।"],
    ["COGS (Cost of goods sold)", "বিক্রীত পণ্যের খরচ", "The direct cost of the goods sold in a period.", "নির্দিষ্ট সময়ে বিক্রি হওয়া পণ্যের সরাসরি খরচ।"],
    ["Multi-currency", "মাল্টি-কারেন্সি", "Recording transactions in foreign currencies with exchange-rate conversion.", "বৈদেশিক মুদ্রায় লেনদেন রেকর্ড করা, বিনিময় হারে রূপান্তরসহ।"],
    ["Exchange gain / loss", "বিনিময় লাভ / ক্ষতি", "The difference caused by a change in exchange rate between invoice and payment.", "ইনভয়েস আর পেমেন্টের মধ্যে বিনিময় হার বদলানোয় সৃষ্ট পার্থক্য।"],
    ["Revaluation", "পুনর্মূল্যায়ন", "Restating foreign-currency balances at the period-end exchange rate.", "মেয়াদ শেষের বিনিময় হারে বৈদেশিক মুদ্রার ব্যালেন্স নতুন করে দেখানো।"],
    ["Intercompany transaction", "আন্তঃকোম্পানি লেনদেন", "A sale, purchase or loan between companies in the same group.", "একই গ্রুপের কোম্পানিগুলোর মধ্যে বিক্রি, কেনা বা ঋণ।", "/lab/0098-odoo-consolidation-group-companies-bangladesh"],
    ["Sister concern", "সহযোগী প্রতিষ্ঠান", "A separate company owned by the same group or family.", "একই গ্রুপ বা পরিবারের মালিকানাধীন আলাদা কোম্পানি।", "/lab/0098-odoo-consolidation-group-companies-bangladesh"],
    ["Petty cash", "খুচরা নগদ তহবিল", "A small cash fund for minor expenses.", "ছোটখাটো খরচের জন্য অল্প নগদ টাকার তহবিল।"],
    ["Expense claim", "খরচের দাবি", "An employee's request to be reimbursed for business spending.", "ব্যবসার কাজে নিজের টাকায় করা খরচ ফেরত পেতে কর্মীর আবেদন।", "/lab/0096-odoo-expenses-employee-reimbursement-bangladesh"],
    ["Advance to supplier", "সরবরাহকারীকে অগ্রিম", "Payment made to a supplier before the bill is received.", "বিল পাওয়ার আগে সরবরাহকারীকে দেওয়া টাকা।"],
    ["Retention money", "জামানত রাখা টাকা", "A share of a contractor's bill held back until work is accepted.", "কাজ গ্রহণ না হওয়া পর্যন্ত ঠিকাদারের বিলের যে অংশ আটকে রাখা হয়।"],
    ["Provision", "সঞ্চিতি (প্রভিশন)", "An amount set aside for a known future liability, such as bad debts or gratuity.", "জানা ভবিষ্যৎ দায়ের জন্য আলাদা করে রাখা অঙ্ক, যেমন অনাদায়ী পাওনা বা গ্র্যাচুইটি।"],
    ["Bad debt", "অনাদায়ী পাওনা", "A receivable that will not be collected and is written off.", "যে পাওনা আদায় হবে না, তাই খরচে লিখে দেওয়া হয়।"],
    ["Write-off", "রাইট-অফ", "Removing a value from the books as a loss.", "কোনো মূল্য ক্ষতি হিসেবে খাতা থেকে বাদ দেওয়া।"],
    ["Audit", "নিরীক্ষা (অডিট)", "An independent examination of financial records.", "আর্থিক রেকর্ডের স্বাধীন পরীক্ষা।"],
    ["Statutory audit", "বিধিবদ্ধ নিরীক্ষা", "The annual audit required by law for companies, by a chartered accountant firm.", "কোম্পানির জন্য আইনত বাধ্যতামূলক বার্ষিক নিরীক্ষা, চার্টার্ড অ্যাকাউন্ট্যান্ট ফার্ম দিয়ে।"],
    ["IFRS", "IFRS", "International Financial Reporting Standards, adopted in Bangladesh through the FRC.", "আন্তর্জাতিক আর্থিক প্রতিবেদন মানদণ্ড। বাংলাদেশে FRC-র মাধ্যমে গৃহীত।"],
    ["FRC", "ফাইন্যান্সিয়াল রিপোর্টিং কাউন্সিল", "Bangladesh's Financial Reporting Council, which oversees financial reporting standards.", "বাংলাদেশের আর্থিক প্রতিবেদন মানদণ্ড তদারককারী প্রতিষ্ঠান।"],
    ["RJSC", "যৌথ মূলধন কোম্পানি ও ফার্মসমূহের পরিদপ্তর", "The Registrar of Joint Stock Companies and Firms, where companies file annual returns.", "যেখানে কোম্পানিগুলো বার্ষিক রিটার্ন জমা দেয়, সেই নিবন্ধক দপ্তর।", "/lab/0081-rjsc-annual-compliance-efiling-odoo-bangladesh"],
    ["Provident fund (PF)", "ভবিষ্য তহবিল", "A retirement savings fund with employee and employer contributions.", "কর্মী আর মালিকের অবদানে গড়া অবসরকালীন সঞ্চয় তহবিল।", "/lab/0016-odoo-hr-payroll-bangladesh"],
    ["Gratuity", "গ্র্যাচুইটি / আনুতোষিক", "A lump-sum benefit paid on leaving, based on years of service.", "চাকরি ছাড়ার সময় চাকরির বছর অনুযায়ী দেওয়া এককালীন সুবিধা।", "/lab/0016-odoo-hr-payroll-bangladesh"],
    ["WPPF", "শ্রমিকের মুনাফায় অংশগ্রহণ তহবিল", "Workers' Profit Participation Fund: 5% of net profit set aside for workers, under the Labour Act.", "শ্রম আইন অনুযায়ী নিট মুনাফার ৫% শ্রমিকদের জন্য আলাদা রাখা তহবিল।"],
    ["Cheque", "চেক", "A written order to a bank to pay money. Post-dated cheques are still common in Bangladesh.", "ব্যাংককে টাকা দেওয়ার লিখিত নির্দেশ। বাংলাদেশে এখনো অগ্রিম তারিখের চেক প্রচলিত।"],
    ["PDC (Post-dated cheque)", "অগ্রিম তারিখের চেক", "A cheque dated in the future, tracked until it can be deposited.", "ভবিষ্যৎ তারিখের চেক, জমা দেওয়া যাওয়া পর্যন্ত যা ট্র্যাক করতে হয়।"],
    ["MFS", "মোবাইল আর্থিক সেবা", "Mobile Financial Services such as bKash, Nagad and Rocket.", "বিকাশ, নগদ, রকেটের মতো মোবাইল ফাইন্যান্সিয়াল সার্ভিস।"],
    ["BEFTN", "BEFTN", "Bangladesh Electronic Funds Transfer Network, used for salary and vendor payments.", "বাংলাদেশ ইলেকট্রনিক ফান্ডস ট্রান্সফার নেটওয়ার্ক, বেতন আর ভেন্ডর পেমেন্টে ব্যবহৃত।"],
    ["RTGS", "RTGS", "Real-Time Gross Settlement for high-value, same-day bank transfers.", "বড় অঙ্কের, একই দিনের ব্যাংক ট্রান্সফারের রিয়েল-টাইম গ্রস সেটেলমেন্ট।"],
    ["NPSB", "NPSB", "National Payment Switch Bangladesh, the inter-bank card and instant transfer network.", "ন্যাশনাল পেমেন্ট সুইচ বাংলাদেশ, আন্তঃব্যাংক কার্ড আর তাৎক্ষণিক ট্রান্সফার নেটওয়ার্ক।"],
    ["Bank statement import", "ব্যাংক স্টেটমেন্ট ইমপোর্ট", "Loading a bank's statement file into the ERP for reconciliation.", "মিলকরণের জন্য ব্যাংকের স্টেটমেন্ট ফাইল ERP-তে তোলা।"],
    ["Overdraft (OD)", "ওভারড্রাফট", "A bank facility to withdraw beyond the account balance, up to a limit.", "একটা সীমা পর্যন্ত হিসাবের ব্যালেন্সের বেশি তোলার ব্যাংক সুবিধা।"],
    ["CC (Cash credit) loan", "ক্যাশ ক্রেডিট ঋণ", "A revolving working-capital loan against stock or receivables.", "স্টক বা পাওনার বিপরীতে ঘূর্ণায়মান চলতি মূলধন ঋণ।"],
    ["Standard cost", "মানক খরচ", "A predetermined cost per unit used for valuation and variance analysis.", "মূল্যায়ন আর ব্যবধান বিশ্লেষণে ব্যবহৃত, আগে থেকে ঠিক করা প্রতি ইউনিটের খরচ।", "/lab/0011-odoo-inventory-valuation-cheatsheet"],
    ["Costing method", "কস্টিং পদ্ধতি", "How inventory cost is calculated: standard, average (AVCO) or FIFO.", "স্টকের খরচ কীভাবে হিসাব হবে: মানক, গড় (AVCO) বা FIFO।", "/lab/0011-odoo-inventory-valuation-cheatsheet"],
    ["Perpetual valuation", "চলমান মূল্যায়ন", "Stock value posted to accounts automatically with every movement.", "প্রতিটি স্টক মুভমেন্টে স্বয়ংক্রিয়ভাবে হিসাবে পোস্ট হওয়া স্টকের মূল্য।", "/lab/0011-odoo-inventory-valuation-cheatsheet"],
    ["Periodic valuation", "পর্যায়ক্রমিক মূল্যায়ন", "Stock value adjusted in the accounts only at period end.", "মেয়াদ শেষে একবারই হিসাবে সমন্বয় করা স্টকের মূল্য।"],
    ["Contingency", "কন্টিনজেন্সি", "A reserve in the budget for unexpected costs, typically 15–25% on ERP projects.", "অপ্রত্যাশিত খরচের জন্য বাজেটে রাখা সংরক্ষিত অংশ। ERP প্রজেক্টে সাধারণত ১৫–২৫%।", "/lab/0050-hidden-erp-costs-bangladesh"],
    ["Opportunity cost", "সুযোগ ব্যয়", "The value of what staff could have done instead, such as time spent on the ERP project.", "কর্মীরা অন্য যে কাজ করতে পারতেন তার মূল্য, যেমন ERP প্রজেক্টে দেওয়া সময়।", "/lab/0050-hidden-erp-costs-bangladesh"],
    ["Capex / Opex", "মূলধনী / পরিচালন ব্যয়", "Capital expenditure (long-term assets) versus operating expenditure (running costs).", "মূলধনী ব্যয় (দীর্ঘমেয়াদি সম্পদ) বনাম পরিচালন ব্যয় (চলমান খরচ)।"],
    ["Treasury challan", "ট্রেজারি চালান", "The government payment slip used to deposit taxes and duties.", "কর আর শুল্ক জমা দেওয়ার সরকারি পেমেন্ট স্লিপ।"],
    ["A-challan", "এ-চালান (অটোমেটেড চালান)", "The online automated challan system for paying government dues.", "সরকারি পাওনা পরিশোধের অনলাইন স্বয়ংক্রিয় চালান ব্যবস্থা।"]
  ]
};
