// Glossary — HR, payroll & labour law (Bangladesh).
module.exports = {
  id: "hr", en: "HR, payroll & labour", bn: "HR, পে-রোল ও শ্রম",
  terms: [
    ["Bangladesh Labour Act 2006", "বাংলাদেশ শ্রম আইন ২০০৬", "The main law on employment, wages, hours, leave and benefits, as amended.", "চাকরি, মজুরি, কর্মঘণ্টা, ছুটি আর সুবিধার মূল আইন (সংশোধিত)।"],
    ["Bangladesh Labour Rules 2015", "বাংলাদেশ শ্রম বিধিমালা ২০১৫", "The rules under the Labour Act, including festival bonus and record-keeping.", "শ্রম আইনের অধীন বিধিমালা, উৎসব বোনাস আর রেকর্ড রাখার নিয়মসহ।"],
    ["Minimum Wage Board", "ন্যূনতম মজুরি বোর্ড", "The government body that sets sector-wise minimum wages.", "খাতভিত্তিক ন্যূনতম মজুরি নির্ধারণকারী সরকারি সংস্থা।", "/tools/rmg-wage-calculator/"],
    ["Wage grade", "মজুরি গ্রেড", "A wage-board category with a set basic and gross. RMG has 5 worker grades.", "নির্দিষ্ট মূল ও মোট মজুরিসহ মজুরি বোর্ডের একটি শ্রেণি। RMG-তে শ্রমিকদের ৫টি গ্রেড।", "/tools/rmg-wage-calculator/"],
    ["Basic wage", "মূল মজুরি", "The base component of pay, on which OT, increments and bonuses are calculated.", "বেতনের মূল অংশ, যার ওপর OT, ইনক্রিমেন্ট আর বোনাস হিসাব হয়।", "/tools/rmg-wage-calculator/"],
    ["Gross wage", "মোট মজুরি", "Basic plus house rent, medical, conveyance and food allowances.", "মূল মজুরি, সঙ্গে বাড়ি ভাড়া, চিকিৎসা, যাতায়াত আর খাদ্য ভাতা।", "/tools/rmg-wage-calculator/"],
    ["House rent allowance", "বাড়ি ভাড়া ভাতা", "In the RMG structure, 50% of basic.", "RMG কাঠামোতে মূল মজুরির ৫০%।"],
    ["Medical / conveyance / food allowance", "চিকিৎসা / যাতায়াত / খাদ্য ভাতা", "Fixed allowances in the RMG wage structure: ৳750, ৳450 and ৳1,250.", "RMG মজুরি কাঠামোর নির্দিষ্ট ভাতা: ৳৭৫০, ৳৪৫০ আর ৳১,২৫০।"],
    ["Annual increment", "বার্ষিক ইনক্রিমেন্ট", "A yearly raise. For RMG workers it's 9% of basic from December 2024.", "বছরে একবার বেতন বৃদ্ধি। RMG শ্রমিকদের জন্য ডিসেম্বর ২০২৪ থেকে মূল মজুরির ৯%।", "/compliance-watch/"],
    ["Overtime (OT)", "অধিকাল (ওভারটাইম)", "Work beyond normal hours, paid at twice the basic hourly rate (Labour Act s.108).", "স্বাভাবিক সময়ের বাইরে কাজ, মূল ঘণ্টাপ্রতি হারের দ্বিগুণে পরিশোধ্য (শ্রম আইন ধারা ১০৮)।", "/tools/rmg-wage-calculator/"],
    ["OT rate", "OT হার", "Basic ÷ 208 × 2 per hour, in common practice.", "প্রচলিত হিসাবে প্রতি ঘণ্টায় মূল মজুরি ÷ ২০৮ × ২।", "/tools/rmg-wage-calculator/"],
    ["Working hours", "কর্মঘণ্টা", "8 hours a day and 48 a week, with overtime limits set by law.", "দিনে ৮ ঘণ্টা আর সপ্তাহে ৪৮ ঘণ্টা, আইনে নির্ধারিত OT সীমাসহ।"],
    ["Festival bonus", "উৎসব ভাতা", "Two per year, each up to one month's basic, after one year of service.", "এক বছর চাকরির পর বছরে দুটি, প্রতিটি সর্বোচ্চ এক মাসের মূল মজুরি।", "/tools/rmg-wage-calculator/"],
    ["Attendance bonus", "হাজিরা বোনাস", "An incentive for full attendance. It's factory policy, not law.", "পূর্ণ উপস্থিতির প্রণোদনা। এটা কারখানার নীতি, আইন নয়।"],
    ["Night allowance", "রাত্রিকালীন ভাতা", "An extra payment for night-shift work, per factory policy or agreement.", "রাতের শিফটের জন্য বাড়তি পেমেন্ট, কারখানার নীতি বা চুক্তি অনুযায়ী।"],
    ["Absence deduction", "অনুপস্থিতির কর্তন", "A proportionate deduction for unauthorised absence.", "অননুমোদিত অনুপস্থিতির জন্য আনুপাতিক কর্তন।"],
    ["Stamp deduction", "স্ট্যাম্প কর্তন", "The revenue stamp amount deducted on salary receipts, where applicable.", "প্রযোজ্য ক্ষেত্রে বেতনের রসিদে রেভিনিউ স্ট্যাম্পের অঙ্ক কর্তন।"],
    ["Payslip", "পে-স্লিপ", "The statement of an employee's earnings and deductions for a period.", "নির্দিষ্ট সময়ের জন্য কর্মীর আয় আর কর্তনের বিবরণ।", "/lab/0016-odoo-hr-payroll-bangladesh"],
    ["Salary structure", "বেতন কাঠামো", "The set of salary rules (components) applied to a group of employees.", "একদল কর্মীর ওপর প্রযোজ্য বেতনের নিয়মের (অংশের) সেট।", "/lab/0022-bgmea-wage-board-odoo-payroll"],
    ["Salary rule", "স্যালারি রুল", "In Odoo, a formula that calculates one payslip line.", "Odoo-তে পে-স্লিপের একটি লাইন হিসাবের ফর্মুলা।", "/lab/0022-bgmea-wage-board-odoo-payroll"],
    ["Payroll batch", "পে-রোল ব্যাচ", "Generating payslips for many employees at once.", "একসঙ্গে অনেক কর্মীর পে-স্লিপ তৈরি।"],
    ["Bank advice / salary file", "ব্যাংক অ্যাডভাইস / বেতন ফাইল", "The file sent to the bank to transfer salaries.", "বেতন ট্রান্সফারের জন্য ব্যাংকে পাঠানো ফাইল।"],
    ["Wages through MFS", "MFS-এ মজুরি পরিশোধ", "Paying workers' wages through bKash, Nagad or similar.", "বিকাশ, নগদ বা অনুরূপ মাধ্যমে শ্রমিকদের মজুরি দেওয়া।"],
    ["Attendance", "হাজিরা", "Recording employees' check-in and check-out times.", "কর্মীদের আসা-যাওয়ার সময় রেকর্ড করা।"],
    ["Biometric device", "বায়োমেট্রিক ডিভাইস", "A fingerprint or face attendance machine, often integrated with payroll.", "আঙুলের ছাপ বা মুখ দেখে হাজিরার যন্ত্র, প্রায়ই পে-রোলের সঙ্গে যুক্ত।", "/lab/0050-hidden-erp-costs-bangladesh"],
    ["Shift", "শিফট", "A defined working period, such as day, evening or night.", "নির্দিষ্ট কাজের সময়, যেমন দিন, সন্ধ্যা বা রাত।"],
    ["Roster", "রোস্টার", "The schedule assigning employees to shifts.", "কর্মীদের শিফটে বসানোর সময়সূচি।"],
    ["Leave types", "ছুটির ধরন", "Casual (10 days), sick (14), earned (1 day per 18 worked), festival (11), and maternity (16 weeks) under the Labour Act.", "শ্রম আইন অনুযায়ী নৈমিত্তিক (১০ দিন), অসুস্থতা (১৪), অর্জিত (প্রতি ১৮ কর্মদিবসে ১ দিন), উৎসব (১১) আর মাতৃত্বকালীন (১৬ সপ্তাহ) ছুটি।"],
    ["Earned leave encashment", "অর্জিত ছুটির নগদায়ন", "Paying out unused earned leave, as allowed by law.", "আইন অনুযায়ী অব্যবহৃত অর্জিত ছুটির টাকা দেওয়া।"],
    ["Maternity benefit", "প্রসূতি কল্যাণ সুবিধা", "Paid maternity leave of 16 weeks (8 before and 8 after delivery) under the Labour Act.", "শ্রম আইন অনুযায়ী ১৬ সপ্তাহের সবেতন মাতৃত্বকালীন ছুটি (প্রসবের আগে ৮, পরে ৮)।"],
    ["Probation", "শিক্ষানবিশকাল", "The trial period for a new employee.", "নতুন কর্মীর পরীক্ষামূলক সময়।"],
    ["Apprentice", "শিক্ষানবিশ", "A trainee worker. The RMG apprentice wage is ৳9,875 for up to 3+3 months.", "প্রশিক্ষণার্থী শ্রমিক। RMG-তে শিক্ষানবিশের মজুরি ৳৯,৮৭৫, সর্বোচ্চ ৩+৩ মাস।", "/tools/rmg-wage-calculator/"],
    ["Final settlement", "চূড়ান্ত পাওনা পরিশোধ", "Dues paid on resignation or termination: wages, leave, gratuity, notice pay.", "পদত্যাগ বা অব্যাহতিতে দেওয়া পাওনা: মজুরি, ছুটি, গ্র্যাচুইটি, নোটিশ পে।"],
    ["Notice pay", "নোটিশ পে", "Wages paid in lieu of the required notice period.", "প্রয়োজনীয় নোটিশের বদলে দেওয়া মজুরি।"],
    ["Service book", "সার্ভিস বই", "The statutory record of a worker's employment history.", "শ্রমিকের চাকরির ইতিহাসের আইনি রেকর্ড।"],
    ["ID card & appointment letter", "পরিচয়পত্র ও নিয়োগপত্র", "Documents every worker must receive under the Labour Act.", "শ্রম আইন অনুযায়ী প্রত্যেক শ্রমিকের প্রাপ্য ডকুমেন্ট।"],
    ["Employee master", "কর্মী মাস্টার", "The central record of each employee: personal data, grade, bank account, joining date.", "প্রতিটি কর্মীর কেন্দ্রীয় রেকর্ড: ব্যক্তিগত তথ্য, গ্রেড, ব্যাংক হিসাব, যোগদানের তারিখ।"],
    ["Headcount", "কর্মীসংখ্যা", "The number of employees.", "কর্মীর সংখ্যা।"],
    ["Attrition / turnover", "কর্মী ছেড়ে যাওয়ার হার", "The rate at which employees leave.", "যে হারে কর্মীরা চাকরি ছাড়েন।"],
    ["Recruitment", "নিয়োগ", "Finding and hiring staff, from job posting to offer.", "চাকরির বিজ্ঞাপন থেকে অফার পর্যন্ত কর্মী খোঁজা আর নিয়োগ।", "/lab/0097-odoo-recruitment-module-bangladesh"],
    ["Appraisal", "কর্মমূল্যায়ন", "A periodic review of an employee's performance.", "কর্মীর কাজের পর্যায়ক্রমিক মূল্যায়ন।"],
    ["Participation committee", "অংশগ্রহণকারী কমিটি", "A committee of worker and management representatives required under the Labour Act.", "শ্রম আইনে বাধ্যতামূলক শ্রমিক আর মালিকপক্ষের প্রতিনিধি কমিটি।"],
    ["Safety committee", "সেফটি কমিটি", "A committee required in factories with 50+ workers.", "৫০ জনের বেশি শ্রমিকের কারখানায় বাধ্যতামূলক কমিটি।"],
    ["BGMEA / BKMEA", "BGMEA / BKMEA", "The garment and knitwear manufacturers' and exporters' associations.", "পোশাক আর নিটওয়্যার উৎপাদক ও রপ্তানিকারকদের সমিতি।", "/lab/0022-bgmea-wage-board-odoo-payroll"],
    ["DIFE", "কলকারখানা ও প্রতিষ্ঠান পরিদর্শন অধিদপ্তর", "The Department of Inspection for Factories and Establishments, the labour inspectorate.", "কলকারখানা ও প্রতিষ্ঠান পরিদর্শন অধিদপ্তর, শ্রম পরিদর্শনের দপ্তর।"],
    ["Group insurance", "গ্রুপ বিমা", "Insurance covering workers, required in factories of a certain size.", "শ্রমিকদের জন্য বিমা, নির্দিষ্ট আকারের কারখানায় বাধ্যতামূলক।"],
    ["Employment injury scheme", "কর্মক্ষেত্রে দুর্ঘটনা সুরক্ষা প্রকল্প", "The pilot scheme compensating workers injured at work.", "কর্মক্ষেত্রে আহত শ্রমিকদের ক্ষতিপূরণের পরীক্ষামূলক প্রকল্প।"],
    ["Loan / advance recovery", "ঋণ / অগ্রিম আদায়", "Deducting salary advances or loans from future payslips.", "পরের পে-স্লিপগুলো থেকে বেতন-অগ্রিম বা ঋণ কেটে নেওয়া।"],
    ["Investment allowance", "বিনিয়োগ ভাতা (কর রেয়াত)", "An income tax rebate on eligible investments, applied in salary tax.", "যোগ্য বিনিয়োগে আয়কর রেয়াত, বেতনের করে প্রযোজ্য।"],
    ["Tax deduction certificate", "কর কর্তন সনদ", "An annual certificate showing tax deducted from salary.", "বেতন থেকে কাটা করের বার্ষিক সনদ।"],
    ["Personal data", "ব্যক্তিগত তথ্য", "Information about identifiable people, now regulated by the 2026 data protection law.", "শনাক্তযোগ্য মানুষের তথ্য, যা এখন ২০২৬-এর তথ্য সুরক্ষা আইনে নিয়ন্ত্রিত।", "/lab/0078-bangladesh-data-protection-act-cloud-erp"]
  ]
};
