// Glossary — Manufacturing & quality.
module.exports = {
  id: "manufacturing", en: "Manufacturing & quality", bn: "উৎপাদন ও মান",
  terms: [
    ["BOM (Bill of Materials)", "বিল অব ম্যাটেরিয়ালস", "The list of components and quantities needed to make one unit of a product.", "একটি ইউনিট পণ্য তৈরিতে যে উপকরণ আর পরিমাণ লাগে, তার তালিকা।", "/lab/0013-odoo-manufacturing-module-bangladesh"],
    ["Multi-level BOM", "বহুস্তর BOM", "A BOM whose components have their own BOMs (sub-assemblies).", "যে BOM-এর উপকরণের নিজস্ব BOM আছে (সাব-অ্যাসেম্বলি)।", "/lab/0034-odoo-cycle-export-bangladesh"],
    ["Phantom BOM / kit", "ফ্যান্টম BOM / কিট", "A set of components sold or issued together but never stocked as an assembled item.", "একসঙ্গে বিক্রি বা ইস্যু হওয়া উপকরণের সেট, যা জোড়া অবস্থায় কখনো মজুদ হয় না।"],
    ["Routing", "রাউটিং", "The sequence of operations and work centres used to make a product.", "একটি পণ্য তৈরিতে কাজের ধাপ আর ওয়ার্ক সেন্টারের ক্রম।", "/lab/0038-odoo-manufacturing-routing-bangladesh"],
    ["Work centre", "ওয়ার্ক সেন্টার", "A machine, line or team where an operation is performed.", "যে মেশিন, লাইন বা দলে একটি কাজ হয়।", "/lab/0038-odoo-manufacturing-routing-bangladesh"],
    ["Work order", "ওয়ার্ক অর্ডার", "One operation of a manufacturing order at a work centre.", "কোনো ওয়ার্ক সেন্টারে ম্যানুফ্যাকচারিং অর্ডারের একটি কাজ।"],
    ["Manufacturing order (MO)", "উৎপাদন আদেশ", "An order to produce a quantity of a product using a BOM.", "BOM ব্যবহার করে নির্দিষ্ট পরিমাণ পণ্য তৈরির আদেশ।"],
    ["MRP (Material Requirements Planning)", "উপকরণের প্রয়োজন পরিকল্পনা", "Calculating what materials to buy or make, and when, from demand and BOMs.", "চাহিদা আর BOM থেকে কোন উপকরণ কখন কিনতে বা তৈরি করতে হবে তা হিসাব করা।"],
    ["MPS (Master Production Schedule)", "মাস্টার প্রোডাকশন শিডিউল", "The plan of what finished goods to produce in each period.", "প্রতি মেয়াদে কোন তৈরি পণ্য উৎপাদন হবে তার পরিকল্পনা।"],
    ["Capacity planning", "সক্ষমতা পরিকল্পনা", "Checking that machines and people can handle the planned production.", "পরিকল্পিত উৎপাদন সামলাতে মেশিন আর মানুষ যথেষ্ট কি না যাচাই।"],
    ["WIP (Work in Progress)", "চলমান উৎপাদন", "Partly finished goods still on the shop floor.", "কারখানায় থাকা আংশিক তৈরি পণ্য।"],
    ["Finished goods (FG)", "তৈরি পণ্য", "Completed products ready for sale.", "বিক্রির জন্য প্রস্তুত সম্পূর্ণ পণ্য।"],
    ["Raw material (RM)", "কাঁচামাল", "Inputs consumed to make products.", "পণ্য তৈরিতে ব্যবহৃত উপকরণ।"],
    ["Accessories / trims", "অ্যাক্সেসরিজ / ট্রিমস", "Garment components such as buttons, zips, labels and threads.", "বোতাম, চেইন, লেবেল আর সুতার মতো পোশাকের উপকরণ।", "/lab/0033-odoo-rmg-garments-bangladesh"],
    ["By-product", "উপজাত পণ্য", "A secondary product created alongside the main product.", "মূল পণ্যের সঙ্গে তৈরি হওয়া দ্বিতীয় পণ্য।"],
    ["Yield", "ইল্ড (প্রাপ্তি)", "Output quantity as a percentage of input quantity.", "উপকরণের পরিমাণের শতাংশ হিসেবে উৎপাদনের পরিমাণ।"],
    ["Process loss / wastage", "প্রসেস লস / অপচয়", "Material lost during production, often built into the BOM as a percentage.", "উৎপাদনে হারানো উপকরণ, যা প্রায়ই BOM-এ শতাংশ হিসেবে ধরা থাকে।"],
    ["Consumption", "কনজাম্পশন (ব্যবহার)", "Quantity of material actually used against a production order.", "উৎপাদন আদেশের বিপরীতে প্রকৃতপক্ষে ব্যবহৃত উপকরণের পরিমাণ।"],
    ["Rework", "রিওয়ার্ক", "Correcting defective products, which adds cost that should be tracked.", "ত্রুটিপূর্ণ পণ্য ঠিক করা। এতে যে খরচ বাড়ে, তা ট্র্যাক করা উচিত।"],
    ["Subcontracting / job work", "সাবকন্ট্র্যাক্টিং / জব ওয়ার্ক", "Sending material to another factory to perform an operation.", "কোনো কাজ করানোর জন্য অন্য কারখানায় উপকরণ পাঠানো।", "/lab/0063-odoo-subcontracting-rmg-garments-bangladesh"],
    ["Style", "স্টাইল", "In RMG, a garment design with its own BOM, costing and variants.", "RMG-তে একটি পোশাকের ডিজাইন, যার নিজস্ব BOM, কস্টিং আর ভ্যারিয়েন্ট আছে।", "/lab/0033-odoo-rmg-garments-bangladesh"],
    ["Costing sheet", "কস্টিং শিট", "A breakdown of fabric, trims, CM and overheads for a style or product.", "একটি স্টাইল বা পণ্যের ফ্যাব্রিক, ট্রিমস, CM আর ওভারহেডের বিভাজন।"],
    ["CM (Cost of Making)", "কস্ট অব মেকিং", "The labour and overhead charge for making a garment, excluding materials.", "উপকরণ বাদে একটি পোশাক তৈরির শ্রম আর ওভারহেড চার্জ।"],
    ["SMV / SAM", "SMV / SAM", "Standard minute value: the standard time to perform a garment operation.", "স্ট্যান্ডার্ড মিনিট ভ্যালু: পোশাকের একটি কাজ করার মানক সময়।"],
    ["Line efficiency", "লাইন দক্ষতা", "Earned minutes divided by available minutes on a sewing line.", "সেলাই লাইনে অর্জিত মিনিটকে প্রাপ্য মিনিট দিয়ে ভাগ।"],
    ["Marker / cutting", "মার্কার / কাটিং", "Planning how pattern pieces are laid on fabric to minimise waste.", "অপচয় কমাতে ফ্যাব্রিকে প্যাটার্নের টুকরো কীভাবে সাজানো হবে তার পরিকল্পনা।"],
    ["Shade / dye lot", "শেড / ডাই লট", "Fabric dyed in one batch. Mixing lots causes colour variation.", "এক ব্যাচে রং করা ফ্যাব্রিক। লট মেশালে রঙে তারতম্য হয়।", "/lab/0037-odoo-spinning-mill-bangladesh"],
    ["Yarn count", "সুতার কাউন্ট", "A measure of yarn fineness, such as 30s or 40s Ne.", "সুতার সূক্ষ্মতার মাপ, যেমন ৩০ বা ৪০ Ne।", "/lab/0037-odoo-spinning-mill-bangladesh"],
    ["GSM", "GSM", "Grams per square metre: the weight of a fabric.", "প্রতি বর্গমিটারে গ্রাম: ফ্যাব্রিকের ওজন।"],
    ["Production planning & control (PPC)", "উৎপাদন পরিকল্পনা ও নিয়ন্ত্রণ", "The function that schedules production and tracks progress.", "যে বিভাগ উৎপাদনের সময়সূচি করে আর অগ্রগতি ট্র্যাক করে।"],
    ["Shop floor", "কারখানার ফ্লোর", "The production area of a factory.", "কারখানার উৎপাদন এলাকা।"],
    ["OEE", "OEE", "Overall Equipment Effectiveness: availability × performance × quality.", "সামগ্রিক যন্ত্র কার্যকারিতা: প্রাপ্যতা × কর্মক্ষমতা × মান।"],
    ["Downtime", "ডাউনটাইম", "Time a machine is not producing because of breakdown, changeover or no material.", "বিকল, পরিবর্তন বা উপকরণ না থাকায় মেশিন যে সময় উৎপাদন করে না।"],
    ["Changeover / setup time", "চেঞ্জওভার / সেটআপ সময়", "Time to switch a machine from one product to another.", "একটি মেশিনকে এক পণ্য থেকে আরেক পণ্যে বদলাতে যে সময় লাগে।"],
    ["Preventive maintenance", "প্রতিরোধমূলক রক্ষণাবেক্ষণ", "Scheduled maintenance to avoid breakdowns.", "বিকল এড়াতে নির্ধারিত রক্ষণাবেক্ষণ।", "/lab/0061-odoo-preventive-maintenance-bangladesh"],
    ["Corrective maintenance", "সংশোধনমূলক রক্ষণাবেক্ষণ", "Repair after a breakdown.", "বিকল হওয়ার পর মেরামত।"],
    ["MTBF", "MTBF", "Mean time between failures of a machine.", "একটি মেশিনের দুটি বিকলের মধ্যে গড় সময়।"],
    ["Quality control (QC)", "মান নিয়ন্ত্রণ", "Inspecting products or materials against specifications.", "স্পেসিফিকেশনের সঙ্গে পণ্য বা উপকরণ মিলিয়ে পরিদর্শন।", "/lab/0040-odoo-quality-control-iso-bangladesh"],
    ["Quality assurance (QA)", "মান নিশ্চিতকরণ", "The processes that prevent defects, not just detect them.", "যে প্রক্রিয়াগুলো ত্রুটি শুধু ধরে না, ঘটতেই দেয় না।"],
    ["Quality check point", "মান যাচাইয়ের ধাপ", "A mandatory inspection step at receipt, in production or before delivery.", "মাল গ্রহণ, উৎপাদন বা ডেলিভারির আগে বাধ্যতামূলক পরিদর্শনের ধাপ।"],
    ["AQL", "AQL", "Acceptable Quality Level: the sampling standard buyers use for inspections.", "গ্রহণযোগ্য মানের স্তর: পরিদর্শনে বায়ারের ব্যবহৃত নমুনা-মানদণ্ড।"],
    ["Non-conformance (NCR)", "অসঙ্গতি প্রতিবেদন", "A record of a product or process that doesn't meet requirements.", "রিকোয়ারমেন্ট পূরণ করে না এমন পণ্য বা প্রক্রিয়ার রেকর্ড।"],
    ["CAPA", "CAPA", "Corrective and preventive action taken after a quality issue.", "মানের সমস্যার পর নেওয়া সংশোধনমূলক ও প্রতিরোধমূলক ব্যবস্থা।"],
    ["QC hold / release", "QC হোল্ড / রিলিজ", "Blocking stock from use until quality approves it.", "মান অনুমোদন না দেওয়া পর্যন্ত স্টক ব্যবহার আটকে রাখা।", "/lab/0035-odoo-pharma-bangladesh"],
    ["ISO 9001", "ISO 9001", "The international standard for quality management systems.", "মান ব্যবস্থাপনা পদ্ধতির আন্তর্জাতিক মানদণ্ড।", "/lab/0040-odoo-quality-control-iso-bangladesh"],
    ["GMP", "GMP", "Good Manufacturing Practice, required in pharma and food.", "উত্তম উৎপাদন চর্চা, ফার্মা আর খাদ্যে বাধ্যতামূলক।"],
    ["PLM", "PLM", "Product Lifecycle Management: controlled changes to BOMs and designs (ECOs).", "প্রোডাক্ট লাইফসাইকেল ম্যানেজমেন্ট: BOM আর ডিজাইনের নিয়ন্ত্রিত পরিবর্তন (ECO)।"],
    ["ECO (Engineering Change Order)", "ইঞ্জিনিয়ারিং চেঞ্জ অর্ডার", "An approved change to a BOM or routing, with version history.", "BOM বা রাউটিংয়ের অনুমোদিত পরিবর্তন, সংস্করণের ইতিহাসসহ।"],
    ["Recipe / formula", "রেসিপি / ফর্মুলা", "A BOM for process industries such as food, pharma or chemicals.", "খাদ্য, ফার্মা বা রাসায়নিকের মতো প্রসেস শিল্পের BOM।", "/lab/0069-odoo-food-beverage-agro-processing-bangladesh"],
    ["Batch record", "ব্যাচ রেকর্ড", "The documented history of one production batch.", "একটি উৎপাদন ব্যাচের নথিভুক্ত ইতিহাস।"],
    ["Overhead absorption", "ওভারহেড শোষণ", "Allocating indirect factory costs to products.", "কারখানার পরোক্ষ খরচ পণ্যের মধ্যে ভাগ করা।"],
    ["Standard vs actual cost", "মানক বনাম প্রকৃত খরচ", "Comparing planned cost with real cost to find variances.", "ব্যবধান খুঁজতে পরিকল্পিত খরচ আর প্রকৃত খরচ তুলনা।"],
    ["Kanban", "কানবান", "A visual pull system that signals when to replenish.", "কখন পূরণ করতে হবে তা জানানোর দৃশ্যমান পুল পদ্ধতি।"],
    ["Lean", "লিন", "A production philosophy focused on removing waste.", "অপচয় দূর করায় মনোযোগী উৎপাদন দর্শন।"]
  ]
};
