// Glossary — Supply chain, purchasing & inventory.
module.exports = {
  id: "supply", en: "Supply chain & inventory", bn: "সাপ্লাই চেইন ও স্টক",
  terms: [
    ["SKU (Stock Keeping Unit)", "SKU", "A unique code for each distinct product variant that is stocked.", "মজুদ রাখা প্রতিটি আলাদা প্রোডাক্ট ভ্যারিয়েন্টের অনন্য কোড।"],
    ["Product variant", "প্রোডাক্ট ভ্যারিয়েন্ট", "A version of a product that differs by attribute, such as size or colour.", "সাইজ বা রঙের মতো বৈশিষ্ট্যে আলাদা একই প্রোডাক্টের সংস্করণ।"],
    ["Unit of measure (UoM)", "মাপের একক", "The unit an item is counted in, such as pcs, kg, metre, yard or dozen.", "যে এককে আইটেম গোনা হয়, যেমন পিস, কেজি, মিটার, গজ বা ডজন।"],
    ["UoM conversion", "এককের রূপান্তর", "Converting between purchase and stock units, such as rolls to yards.", "কেনার একক আর স্টকের এককের মধ্যে রূপান্তর, যেমন রোল থেকে গজ।"],
    ["Purchase requisition", "ক্রয় অনুরোধ", "An internal request to buy something, before a purchase order is raised.", "পারচেজ অর্ডারের আগে কিছু কেনার অভ্যন্তরীণ অনুরোধ।", "/lab/0015-odoo-purchase-vendor-management-bangladesh"],
    ["RFQ (Request for Quotation)", "কোটেশনের অনুরোধ", "A request to suppliers for prices and terms.", "দাম আর শর্ত জানতে সরবরাহকারীদের কাছে অনুরোধ।"],
    ["Comparative statement (CS)", "তুলনামূলক বিবরণী", "A side-by-side comparison of supplier quotations used for approval.", "অনুমোদনের জন্য সরবরাহকারীদের কোটেশনের পাশাপাশি তুলনা।"],
    ["Purchase order (PO)", "পারচেজ অর্ডার", "A confirmed order to a supplier.", "সরবরাহকারীকে দেওয়া নিশ্চিত অর্ডার।"],
    ["Blanket order", "ব্ল্যাঙ্কেট অর্ডার", "A long-term agreement with a supplier for repeated deliveries at agreed prices.", "সম্মত দামে বারবার সরবরাহের জন্য সরবরাহকারীর সঙ্গে দীর্ঘমেয়াদি চুক্তি।"],
    ["GRN (Goods Received Note)", "মাল গ্রহণ নোট", "The record that goods have arrived and been checked into stock.", "মাল এসে পৌঁছেছে আর যাচাই করে স্টকে তোলা হয়েছে, তার রেকর্ড।"],
    ["Three-way match", "তিন-পথে মিলকরণ", "Checking that the PO, goods receipt and supplier bill agree before paying.", "পেমেন্টের আগে PO, মাল গ্রহণ আর সরবরাহকারীর বিল মেলে কি না যাচাই।", "/lab/0048-odoo-roi-calculator-bangladesh"],
    ["Vendor rating", "ভেন্ডর মূল্যায়ন", "Scoring suppliers on price, quality and on-time delivery.", "দাম, মান আর সময়মতো সরবরাহের ভিত্তিতে সরবরাহকারীদের নম্বর দেওয়া।"],
    ["Lead time", "লিড টাইম", "The time between ordering and receiving goods.", "অর্ডার দেওয়া থেকে মাল হাতে পাওয়া পর্যন্ত সময়।"],
    ["Safety stock", "সেফটি স্টক", "Extra stock held to cover demand or supply uncertainty.", "চাহিদা বা সরবরাহের অনিশ্চয়তা সামলাতে রাখা বাড়তি স্টক।"],
    ["Reorder point / min-max", "রি-অর্ডার পয়েন্ট / মিন-ম্যাক্স", "Stock level rules that trigger replenishment automatically.", "যে স্টক-মাত্রার নিয়মে স্বয়ংক্রিয়ভাবে পুনরায় অর্ডার হয়।", "/lab/0039-odoo-reordering-rules-mto-bangladesh"],
    ["MTO (Make to Order)", "অর্ডার অনুযায়ী তৈরি", "Producing or buying only after a customer order is received.", "কাস্টমারের অর্ডার পাওয়ার পরই উৎপাদন বা কেনা।", "/lab/0039-odoo-reordering-rules-mto-bangladesh"],
    ["MTS (Make to Stock)", "স্টকের জন্য তৈরি", "Producing to forecast and holding finished stock.", "পূর্বাভাস অনুযায়ী উৎপাদন করে তৈরি পণ্য মজুদ রাখা।"],
    ["Warehouse", "ওয়্যারহাউস / গুদাম", "A physical site where stock is held.", "যে জায়গায় স্টক রাখা হয়।"],
    ["Location / bin", "লোকেশন / বিন", "A specific place inside a warehouse, such as a rack, shelf or bin.", "গুদামের ভেতরের নির্দিষ্ট জায়গা, যেমন র‍্যাক, তাক বা বিন।"],
    ["Stock move", "স্টক মুভ", "Any movement of stock from one location to another.", "এক লোকেশন থেকে আরেক লোকেশনে স্টকের যেকোনো চলাচল।"],
    ["Internal transfer", "অভ্যন্তরীণ স্থানান্তর", "Moving stock between your own warehouses or locations.", "নিজের গুদাম বা লোকেশনের মধ্যে স্টক সরানো।"],
    ["Picking / packing / delivery", "পিকিং / প্যাকিং / ডেলিভারি", "The steps to prepare and ship a customer order.", "কাস্টমারের অর্ডার প্রস্তুত করে পাঠানোর ধাপগুলো।"],
    ["Delivery challan", "ডেলিভারি চালান", "The document that accompanies goods on dispatch.", "মাল পাঠানোর সময় সঙ্গে যাওয়া ডকুমেন্ট।"],
    ["Gate pass", "গেট পাস", "Authorisation for goods or vehicles to leave the premises.", "মাল বা গাড়িকে প্রাঙ্গণ থেকে বের হওয়ার অনুমতি।"],
    ["Lot / batch", "লট / ব্যাচ", "A group of items produced or received together and tracked as one.", "একসঙ্গে উৎপাদিত বা গৃহীত আইটেমের দল, যা একক হিসেবে ট্র্যাক হয়।"],
    ["Serial number", "সিরিয়াল নম্বর", "A unique number tracking one individual item.", "একটি নির্দিষ্ট আইটেম ট্র্যাক করার অনন্য নম্বর।"],
    ["Traceability", "ট্রেসেবিলিটি", "The ability to follow a lot from supplier through production to customer.", "সরবরাহকারী থেকে উৎপাদন হয়ে কাস্টমার পর্যন্ত একটি লট অনুসরণ করার সক্ষমতা।", "/lab/0079-eudr-odoo-traceability-rubber-wood-furniture-bangladesh"],
    ["Expiry date / FEFO", "মেয়াদ / FEFO", "First Expired, First Out: issuing the stock that expires soonest first.", "যার মেয়াদ আগে শেষ, সেটা আগে বের করা।", "/lab/0035-odoo-pharma-bangladesh"],
    ["FIFO", "FIFO", "First In, First Out: the oldest stock is issued (or costed) first.", "আগে এলো, আগে গেল: সবচেয়ে পুরোনো স্টক আগে বের হয় (বা খরচ ধরা হয়)।", "/lab/0011-odoo-inventory-valuation-cheatsheet"],
    ["AVCO (Average cost)", "গড় খরচ পদ্ধতি", "Valuing stock at the weighted average cost of units on hand.", "হাতে থাকা ইউনিটের ভারিত গড় খরচে স্টকের মূল্য ধরা।", "/lab/0011-odoo-inventory-valuation-cheatsheet"],
    ["Landed cost", "ল্যান্ডেড কস্ট", "Purchase price plus freight, insurance, duties and clearing charges to get goods into your store.", "কেনার দাম, সঙ্গে ফ্রেইট, বিমা, শুল্ক আর খালাসের খরচ, যা দিয়ে মাল গুদামে পৌঁছায়।", "/tools/import-duty-calculator/"],
    ["Cycle count", "চক্রাকার গণনা", "Counting a portion of stock regularly instead of one annual full count.", "বছরে একবার পুরো গণনার বদলে নিয়মিত স্টকের একটা অংশ গোনা।"],
    ["Physical inventory", "বাস্তব স্টক গণনা", "Counting all stock and adjusting the system to match.", "সব স্টক গুনে সিস্টেমকে তার সঙ্গে মেলানো।"],
    ["Stock adjustment", "স্টক সমন্বয়", "An entry correcting system stock to the counted quantity.", "গোনা পরিমাণের সঙ্গে সিস্টেমের স্টক মেলানোর এন্ট্রি।"],
    ["Dead / slow-moving stock", "অচল / ধীরগতির স্টক", "Items with no or little movement over a long period.", "দীর্ঘ সময় ধরে যে আইটেম নড়ে না বা খুব কম নড়ে।"],
    ["Inventory turnover", "স্টক আবর্তন", "How many times stock is used or sold in a year.", "বছরে কতবার স্টক ব্যবহার বা বিক্রি হয়।"],
    ["Stock days / days of cover", "স্টক দিবস", "How many days current stock will last at normal usage.", "স্বাভাবিক ব্যবহারে বর্তমান স্টক কত দিন চলবে।"],
    ["ABC analysis", "ABC বিশ্লেষণ", "Classifying items by value so the most valuable get the tightest control.", "মূল্য অনুযায়ী আইটেম ভাগ করা, যাতে সবচেয়ে দামিগুলো সবচেয়ে কড়া নিয়ন্ত্রণে থাকে।"],
    ["Barcode", "বারকোড", "A scannable code identifying a product, lot or location.", "প্রোডাক্ট, লট বা লোকেশন চেনার স্ক্যান করা যায় এমন কোড।", "/lab/0065-odoo-barcode-warehouse-scanning-bangladesh"],
    ["Putaway rule", "পুটঅ্যাওয়ে রুল", "A rule that decides where received goods are stored.", "গ্রহণ করা মাল কোথায় রাখা হবে তা ঠিক করার নিয়ম।"],
    ["Consignment stock", "কনসাইনমেন্ট স্টক", "Stock held at your site but still owned by the supplier (or at a customer, still yours).", "আপনার জায়গায় রাখা অথচ সরবরাহকারীর মালিকানাধীন স্টক (বা কাস্টমারের কাছে রাখা আপনার স্টক)।"],
    ["Dropship", "ড্রপশিপ", "The supplier ships directly to your customer.", "সরবরাহকারী সরাসরি আপনার কাস্টমারকে মাল পাঠায়।"],
    ["Backorder", "ব্যাকঅর্ডার", "The part of an order not yet delivered because of a shortage.", "ঘাটতির কারণে অর্ডারের যে অংশ এখনো পাঠানো হয়নি।"],
    ["Return (RMA)", "ফেরত (RMA)", "Goods sent back by a customer or to a supplier, with authorisation.", "অনুমোদনসহ কাস্টমারের ফেরত পাঠানো, বা সরবরাহকারীকে ফেরত দেওয়া মাল।"],
    ["Scrap", "স্ক্র্যাপ", "Damaged or unusable stock removed from inventory.", "নষ্ট বা ব্যবহার-অযোগ্য স্টক, যা মজুদ থেকে সরানো হয়।"],
    ["Distributor / dealer", "ডিস্ট্রিবিউটর / ডিলার", "A reseller who buys from the company and sells in a territory.", "যে পুনর্বিক্রেতা কোম্পানি থেকে কিনে নির্দিষ্ট এলাকায় বিক্রি করেন।"],
    ["Secondary sales", "সেকেন্ডারি সেলস", "Sales from distributors to retailers, as opposed to primary sales from company to distributor.", "ডিস্ট্রিবিউটর থেকে খুচরা বিক্রেতার কাছে বিক্রি, কোম্পানি থেকে ডিস্ট্রিবিউটরের প্রাইমারি সেলস নয়।"],
    ["Price list", "মূল্য তালিকা", "A set of prices for a customer group, channel or currency.", "কোনো কাস্টমার গ্রুপ, চ্যানেল বা মুদ্রার জন্য দামের তালিকা।"],
    ["Quotation / sales order", "কোটেশন / সেলস অর্ডার", "A price offer to a customer, and the confirmed order once accepted.", "কাস্টমারকে দেওয়া দামের প্রস্তাব, আর গ্রহণের পর নিশ্চিত অর্ডার।"],
    ["Proforma invoice (PI)", "প্রোফর্মা ইনভয়েস", "A preliminary invoice used by buyers to open an LC or arrange payment.", "LC খোলা বা পেমেন্টের ব্যবস্থা করতে বায়ারের ব্যবহৃত প্রাথমিক ইনভয়েস।", "/lab/0020-lc-management-odoo-bangladesh"],
    ["Incoterms", "ইনকোটার্মস", "Standard trade terms (FOB, CIF, EXW…) that set who pays for and bears the risk of transport.", "পরিবহনের খরচ আর ঝুঁকি কে বহন করবে তা ঠিক করার আন্তর্জাতিক বাণিজ্য শর্ত (FOB, CIF, EXW…)।"],
    ["FOB", "FOB", "Free On Board: the seller's responsibility ends when goods are loaded on the ship.", "ফ্রি অন বোর্ড: জাহাজে মাল ওঠা পর্যন্ত বিক্রেতার দায়িত্ব।"],
    ["CIF", "CIF", "Cost, Insurance and Freight: the seller pays the freight and insurance to the destination port.", "কস্ট, ইনস্যুরেন্স অ্যান্ড ফ্রেইট: গন্তব্য বন্দর পর্যন্ত ফ্রেইট আর বিমা বিক্রেতা দেন।", "/tools/import-duty-calculator/"],
    ["C&F agent", "C&F এজেন্ট", "A clearing and forwarding agent who clears goods through customs.", "যে ক্লিয়ারিং অ্যান্ড ফরোয়ার্ডিং এজেন্ট কাস্টমস থেকে মাল খালাস করেন।", "/lab/0070-odoo-freight-forwarding-cf-agents-bangladesh"],
    ["Freight forwarder", "ফ্রেইট ফরোয়ার্ডার", "A company that arranges transport of shipments.", "যে প্রতিষ্ঠান চালান পরিবহনের ব্যবস্থা করে।", "/lab/0070-odoo-freight-forwarding-cf-agents-bangladesh"],
    ["Container (FCL / LCL)", "কন্টেইনার (FCL / LCL)", "Full container load versus less than a container load (shared).", "পুরো কন্টেইনার বনাম ভাগাভাগি করা আংশিক কন্টেইনার।"],
    ["ICD", "ইনল্যান্ড কন্টেইনার ডিপো", "An inland container depot, such as Kamalapur ICD.", "দেশের ভেতরের কন্টেইনার ডিপো, যেমন কমলাপুর ICD।"],
    ["Demurrage", "ডেমারেজ", "Charges for keeping a container or goods at port beyond the free time.", "বিনামূল্যের সময়ের বেশি বন্দরে কন্টেইনার বা মাল রাখার চার্জ।"],
    ["Forecast", "পূর্বাভাস", "An estimate of future demand used for planning purchases and production.", "কেনা আর উৎপাদন পরিকল্পনার জন্য ভবিষ্যৎ চাহিদার অনুমান।"],
    ["Demand planning", "চাহিদা পরিকল্পনা", "Aligning purchasing and production with expected sales.", "প্রত্যাশিত বিক্রির সঙ্গে কেনা আর উৎপাদন মেলানো।"],
    ["Cold chain", "কোল্ড চেইন", "Temperature-controlled storage and transport for perishables.", "পচনশীল পণ্যের জন্য তাপমাত্রা-নিয়ন্ত্রিত সংরক্ষণ আর পরিবহন।", "/lab/0088-odoo-cold-storage-potato-agri-warehousing-bangladesh"],
    ["Weighbridge", "ওয়েব্রিজ", "A large scale for weighing loaded vehicles at the gate.", "গেটে ভরা গাড়ি মাপার বড় ওজন যন্ত্র।", "/lab/0056-odoo-iot-box-bangladesh"],
    ["Courier / COD reconciliation", "কুরিয়ার / COD মিলকরণ", "Matching cash-on-delivery collections from couriers against orders.", "কুরিয়ারের ক্যাশ-অন-ডেলিভারি আদায় অর্ডারের সঙ্গে মেলানো।"],
    ["Replenishment", "পুনঃপূরণ", "Refilling stock by purchase, production or transfer when it runs low.", "স্টক কমে গেলে কেনা, উৎপাদন বা ট্রান্সফার করে আবার পূরণ করা।", "/lab/0039-odoo-reordering-rules-mto-bangladesh"],
    ["Vendor price list", "ভেন্ডর মূল্য তালিকা", "Agreed supplier prices and minimum quantities stored on products.", "প্রোডাক্টে সংরক্ষিত সরবরাহকারীর সম্মত দাম আর সর্বনিম্ন পরিমাণ।"]
  ]
};
