// Glossary — VAT, income tax & NBR (Bangladesh).
module.exports = {
  id: "tax", en: "VAT, tax & NBR", bn: "VAT, কর ও NBR",
  terms: [
    ["NBR", "জাতীয় রাজস্ব বোর্ড", "The National Board of Revenue, Bangladesh's tax and customs authority.", "জাতীয় রাজস্ব বোর্ড, বাংলাদেশের কর ও শুল্ক কর্তৃপক্ষ।", "/lab/0003-nbr-vat-compliance-odoo-bangladesh"],
    ["VAT (Value Added Tax)", "মূল্য সংযোজন কর (মূসক)", "A consumption tax charged at each stage of supply. The standard rate in Bangladesh is 15%.", "সরবরাহের প্রতিটি ধাপে আরোপিত ভোগ কর। বাংলাদেশে মানক হার ১৫%।", "/tools/vat-mushak-helper/"],
    ["Mushak", "মূসক", "The Bangla abbreviation for VAT. It also names the numbered VAT forms (Mushak 6.3, 9.1…).", "মূল্য সংযোজন করের বাংলা সংক্ষিপ্ত রূপ। নম্বরযুক্ত VAT ফর্মগুলোর নামও এটাই (মূসক ৬.৩, ৯.১…)।", "/tools/vat-mushak-helper/"],
    ["VAT & SD Act 2012", "মূসক ও সম্পূরক শুল্ক আইন ২০১২", "The law governing VAT and supplementary duty, in force since July 2019.", "VAT আর সম্পূরক শুল্কের আইন, জুলাই ২০১৯ থেকে কার্যকর।"],
    ["VAT & SD Rules 2016", "মূসক ও সম্পূরক শুল্ক বিধিমালা ২০১৬", "The rules under the Act that prescribe the Mushak forms and procedures.", "আইনের অধীন বিধিমালা, যা মূসক ফর্ম আর পদ্ধতি নির্ধারণ করে।"],
    ["BIN", "ব্যবসায় সনাক্তকরণ নম্বর", "Business Identification Number: the 13-digit VAT registration number.", "ব্যবসায় সনাক্তকরণ নম্বর: ১৩ অঙ্কের VAT নিবন্ধন নম্বর।", "/compliance-watch/"],
    ["e-VAT", "ই-ভ্যাট", "NBR's online system for VAT registration, returns and payments.", "VAT নিবন্ধন, রিটার্ন আর পেমেন্টের জন্য NBR-এর অনলাইন ব্যবস্থা।"],
    ["VAT registration", "VAT নিবন্ধন", "Mandatory for turnover above ৳50 lakh (and for importers and exporters).", "৳৫০ লাখের বেশি টার্নওভারে (আর আমদানিকারক ও রপ্তানিকারকের জন্য) বাধ্যতামূলক।", "/tools/vat-mushak-helper/"],
    ["Turnover tax enlistment", "টার্নওভার করে তালিকাভুক্তি", "The simplified regime for small businesses with turnover up to ৳50 lakh.", "৳৫০ লাখ পর্যন্ত টার্নওভারের ছোট ব্যবসার সরলীকৃত ব্যবস্থা।", "/compliance-watch/"],
    ["Turnover tax", "টার্নওভার কর", "Tax on small businesses' turnover. Under the Finance Act 2026 it's moving to a fixed amount set by NBR (capped at ৳2 lakh).", "ছোট ব্যবসার টার্নওভারের ওপর কর। অর্থ আইন ২০২৬ অনুযায়ী এটা NBR-নির্ধারিত নির্দিষ্ট অঙ্কে যাচ্ছে (সর্বোচ্চ ৳২ লাখ)।", "/compliance-watch/"],
    ["Output VAT", "উৎপাদ কর", "VAT charged on your sales.", "আপনার বিক্রির ওপর আরোপিত VAT।"],
    ["Input VAT", "উপকরণ কর", "VAT paid on your purchases and imports.", "আপনার কেনা আর আমদানির ওপর দেওয়া VAT।"],
    ["Input tax credit (rebate)", "উপকরণ কর রেয়াত", "Deducting eligible input VAT from output VAT in the return.", "রিটার্নে উৎপাদ কর থেকে যোগ্য উপকরণ কর বাদ দেওয়া।", "/lab/0082-vat-input-tax-credit-rebate-odoo-bangladesh"],
    ["Negative list", "নেতিবাচক তালিকা", "Inputs on which input credit can't be claimed. Labour was removed from it in 2026.", "যে উপকরণে রেয়াত নেওয়া যায় না তার তালিকা। ২০২৬-এ শ্রম এ তালিকা থেকে বাদ পড়েছে।", "/compliance-watch/"],
    ["Standard rate", "মানক হার", "15%, the default VAT rate.", "১৫%, VAT-এর সাধারণ হার।"],
    ["Reduced rate", "হ্রাসকৃত হার", "Lower VAT rates of 10%, 7.5%, 5% and 2% for specified goods and services.", "নির্দিষ্ট পণ্য ও সেবার জন্য কম VAT হার: ১০%, ৭.৫%, ৫% ও ২%।"],
    ["Zero-rated", "শূন্য হার", "Supplies taxed at 0% (mainly exports) with input credit allowed.", "০% হারে করযোগ্য সরবরাহ (মূলত রপ্তানি), যেখানে উপকরণ কর রেয়াত পাওয়া যায়।"],
    ["Exempt supply", "অব্যাহতিপ্রাপ্ত সরবরাহ", "Supplies with no VAT and no input credit.", "যে সরবরাহে VAT নেই, উপকরণ কর রেয়াতও নেই।"],
    ["Fixed-base VAT", "নির্দিষ্ট ভিত্তির VAT", "VAT charged as a fixed amount per unit, such as per metric tonne of steel.", "প্রতি ইউনিটে নির্দিষ্ট অঙ্কে আরোপিত VAT, যেমন প্রতি মেট্রিক টন স্টিলে।", "/lab/0084-odoo-steel-rerolling-light-engineering-bangladesh"],
    ["Truncated value / trade VAT", "বাণিজ্যিক পর্যায়ের VAT", "The simplified VAT that traders may pay on sales (such as 5% or 7.5%) without input credit.", "ব্যবসায়ীরা রেয়াত ছাড়া বিক্রির ওপর যে সরলীকৃত VAT দিতে পারেন (যেমন ৫% বা ৭.৫%)।"],
    ["SD (Supplementary Duty)", "সম্পূরক শুল্ক", "An additional duty on specified goods and services, charged before VAT.", "নির্দিষ্ট পণ্য ও সেবায় বাড়তি শুল্ক, VAT-এর আগে আরোপিত।", "/tools/vat-mushak-helper/"],
    ["VDS (VAT Deducted at Source)", "উৎসে VAT কর্তন", "Withholding entities deduct VAT from supplier payments and deposit it to the government.", "উৎসে কর্তনকারী সত্তা সরবরাহকারীর পেমেন্ট থেকে VAT কেটে সরকারকে জমা দেয়।", "/tools/vat-mushak-helper/"],
    ["Withholding entity", "উৎসে কর্তনকারী সত্তা", "An organisation required to deduct VAT at source, such as banks, public bodies, NGOs and listed or large companies.", "যে প্রতিষ্ঠানকে উৎসে VAT কাটতে হয়, যেমন ব্যাংক, সরকারি সংস্থা, NGO আর তালিকাভুক্ত বা বড় কোম্পানি।"],
    ["Mushak 2.1", "মূসক ২.১", "The VAT registration or enlistment application form.", "VAT নিবন্ধন বা তালিকাভুক্তির আবেদন ফর্ম।"],
    ["Mushak 4.3", "মূসক ৪.৩", "The input-output coefficient (price declaration) for manufactured goods.", "উৎপাদিত পণ্যের উপকরণ-উৎপাদ সহগ (মূল্য ঘোষণা)।"],
    ["Mushak 6.1", "মূসক ৬.১", "The purchase register.", "ক্রয় হিসাব পুস্তক।"],
    ["Mushak 6.2", "মূসক ৬.২", "The sales register.", "বিক্রয় হিসাব পুস্তক।"],
    ["Mushak 6.2.1", "মূসক ৬.২.১", "The purchase-sales register for traders.", "ব্যবসায়ীদের ক্রয়-বিক্রয় হিসাব পুস্তক।"],
    ["Mushak 6.3", "মূসক ৬.৩", "The tax invoice issued for every taxable supply. It can now be issued from your ERP.", "প্রতিটি করযোগ্য সরবরাহে দেওয়া কর চালানপত্র। এখন ERP থেকেই ইস্যু করা যায়।", "/lab/0018-mushak-63-odoo-bangladesh"],
    ["Mushak 6.4", "মূসক ৬.৪", "The challan for contract manufacturing.", "চুক্তিভিত্তিক উৎপাদনের চালানপত্র।"],
    ["Mushak 6.5", "মূসক ৬.৫", "The transfer challan for moving goods between your own units.", "নিজস্ব ইউনিটের মধ্যে মাল সরানোর হস্তান্তর চালানপত্র।"],
    ["Mushak 6.6", "মূসক ৬.৬", "The VAT deduction at source certificate.", "উৎসে VAT কর্তনের সনদপত্র।"],
    ["Mushak 6.7 / 6.8", "মূসক ৬.৭ / ৬.৮", "Credit note and debit note.", "ক্রেডিট নোট আর ডেবিট নোট।"],
    ["Mushak 6.10", "মূসক ৬.১০", "Statement of purchases and sales above ৳2 lakh per invoice.", "প্রতি চালানে ৳২ লাখের বেশি ক্রয়-বিক্রয়ের বিবরণী।"],
    ["Mushak 9.1", "মূসক ৯.১", "The VAT return, now quarterly under the Finance Act 2026.", "VAT রিটার্ন, অর্থ আইন ২০২৬ অনুযায়ী এখন ত্রৈমাসিক।", "/compliance-watch/"],
    ["Mushak 9.1.1", "মূসক ৯.১.১", "The new VAT return form for registered traders (Finance Act 2026).", "নিবন্ধিত ব্যবসায়ীদের নতুন VAT রিটার্ন ফর্ম (অর্থ আইন ২০২৬)।", "/compliance-watch/"],
    ["Mushak 9.2", "মূসক ৯.২", "The turnover tax return.", "টার্নওভার কর রিটার্ন।"],
    ["Tax period", "করমেয়াদ", "The period a VAT liability is calculated for: one month, with returns now filed per quarter.", "যে সময়ের জন্য VAT দায় হিসাব হয়: এক মাস, আর রিটার্ন এখন প্রতি ত্রৈমাসিকে।"],
    ["Advance VAT deposit", "অগ্রিম VAT জমা", "Under the Finance Act 2026, one-third of the previous quarter's tax deposited within 15 days after each month.", "অর্থ আইন ২০২৬ অনুযায়ী প্রতি মাস শেষের ১৫ দিনের মধ্যে আগের ত্রৈমাসিকের করের এক-তৃতীয়াংশ জমা।", "/compliance-watch/"],
    ["Increasing / decreasing adjustment", "বৃদ্ধিকারী / হ্রাসকারী সমন্বয়", "Additions to or deductions from VAT payable in the return, such as VDS or credit notes.", "রিটার্নে প্রদেয় VAT-এ যোগ বা বিয়োগ, যেমন VDS বা ক্রেডিট নোট।"],
    ["VAT circle / division", "VAT সার্কেল / বিভাগ", "The local VAT office responsible for your business.", "আপনার ব্যবসার দায়িত্বপ্রাপ্ত স্থানীয় VAT অফিস।"],
    ["VAT audit", "VAT অডিট", "An examination of VAT records by the authorities. There's now a defined timeline and best-judgment assessment.", "কর্তৃপক্ষের VAT রেকর্ড পরীক্ষা। এখন নির্দিষ্ট সময়সীমা আর সর্বোত্তম বিচারে কর নির্ধারণের বিধান আছে।"],
    ["EFD / SDC", "EFD / SDC", "Electronic fiscal devices and sales data controllers that NBR requires some retailers to use.", "ইলেকট্রনিক ফিসক্যাল ডিভাইস আর সেলস ডেটা কন্ট্রোলার, যা NBR কিছু খুচরা বিক্রেতার জন্য বাধ্যতামূলক করেছে।"],
    ["SRO", "SRO (বিধিবদ্ধ নিয়ন্ত্রক আদেশ)", "A Statutory Regulatory Order, the instrument NBR uses to set exemptions and rates.", "স্ট্যাটিউটরি রেগুলেটরি অর্ডার, যা দিয়ে NBR অব্যাহতি আর হার নির্ধারণ করে।"],
    ["Finance Act", "অর্থ আইন", "The annual law that enacts the budget's tax changes, usually effective 1 July.", "বাজেটের কর-পরিবর্তন কার্যকর করার বার্ষিক আইন, সাধারণত ১ জুলাই থেকে।", "/compliance-watch/"],
    ["TIN / e-TIN", "করদাতা সনাক্তকরণ নম্বর", "Taxpayer Identification Number for income tax.", "আয়করের জন্য করদাতা সনাক্তকরণ নম্বর।"],
    ["Income Tax Act 2023", "আয়কর আইন ২০২৩", "The current income tax law, which replaced the 1984 Ordinance.", "বর্তমান আয়কর আইন, যা ১৯৮৪-র অধ্যাদেশের জায়গা নিয়েছে।"],
    ["TDS / withholding tax", "উৎসে আয়কর কর্তন", "Income tax deducted from payments to suppliers, contractors and employees.", "সরবরাহকারী, ঠিকাদার আর কর্মীদের পেমেন্ট থেকে কাটা আয়কর।", "/lab/0071-ait-income-tax-withholding-odoo-bangladesh"],
    ["AIT (Advance Income Tax)", "অগ্রিম আয়কর", "Income tax collected in advance, for example at import, adjustable against final tax.", "আগাম আদায় করা আয়কর, যেমন আমদানিতে। চূড়ান্ত করের সঙ্গে সমন্বয়যোগ্য।", "/tools/import-duty-calculator/"],
    ["Withholding tax return", "উৎসে কর রিটার্ন", "The periodic return showing tax deducted at source and deposited.", "উৎসে কাটা ও জমা দেওয়া করের পর্যায়ক্রমিক রিটার্ন।"],
    ["Minimum tax", "ন্যূনতম কর", "A floor on income tax based on turnover. The Finance Act 2026 withdrew the concept.", "টার্নওভারভিত্তিক আয়করের নিম্নসীমা। অর্থ আইন ২০২৬ এই ধারণা তুলে নিয়েছে।", "/compliance-watch/"],
    ["Corporate tax", "কর্পোরেট কর", "Income tax on companies: 27.5% for non-listed, reducible to 25% with full bank-transfer compliance.", "কোম্পানির আয়কর: অতালিকাভুক্তদের ২৭.৫%, সব লেনদেন ব্যাংকে করলে ২৫%।"],
    ["Salary tax / PAYE", "বেতনের কর", "Income tax deducted monthly from employees' salaries.", "কর্মীদের বেতন থেকে মাসে মাসে কাটা আয়কর।", "/lab/0016-odoo-hr-payroll-bangladesh"],
    ["Tax-free threshold", "করমুক্ত আয়সীমা", "The income below which individuals pay no income tax (৳4 lakh for AY 2026-27).", "যে আয়ের নিচে ব্যক্তিকে আয়কর দিতে হয় না (করবর্ষ ২০২৬-২৭-এ ৳৪ লাখ)।"],
    ["Assessment year", "করবর্ষ", "The year in which income of the previous income year is assessed.", "যে বছরে আগের আয়বর্ষের আয় নিরূপণ হয়।"],
    ["Return filing (income tax)", "আয়কর রিটার্ন দাখিল", "Filing the annual income tax return. Companies file by the 15th of the seventh month after year-end.", "বার্ষিক আয়কর রিটার্ন জমা। কোম্পানির জন্য বছর শেষের পর সপ্তম মাসের ১৫ তারিখের মধ্যে।"],
    ["PSR", "রিটার্ন জমার প্রমাণ", "Proof of Submission of Return, required for many transactions.", "রিটার্ন জমার প্রমাণপত্র, অনেক লেনদেনে যা লাগে।"],
    ["Advance tax on retail supplies", "খুচরা সরবরাহে অগ্রিম কর", "A new 0.2% advance tax on payments from retailers to manufacturers, importers and distributors (2026).", "খুচরা বিক্রেতার কাছ থেকে উৎপাদক, আমদানিকারক আর ডিস্ট্রিবিউটরের পেমেন্টে নতুন ০.২% অগ্রিম কর (২০২৬)।", "/compliance-watch/"],
    ["Excise duty", "আবগারি শুল্ক", "Duty on bank balances above ৳4 lakh (from 2026), among other items.", "অন্যান্য বিষয়ের মধ্যে ৳৪ লাখের বেশি ব্যাংক ব্যালেন্সের ওপর শুল্ক (২০২৬ থেকে)।"],
    ["Imported services VAT", "আমদানিকৃত সেবার VAT", "15% VAT on foreign services, now withheld by the paying bank.", "বিদেশি সেবার ওপর ১৫% VAT, এখন পেমেন্টকারী ব্যাংক কেটে রাখে।", "/compliance-watch/"],
    ["Reverse charge", "রিভার্স চার্জ", "The buyer accounts for VAT instead of the seller. It was removed for imported services in 2026.", "বিক্রেতার বদলে ক্রেতা VAT হিসাব করেন। ২০২৬-এ আমদানিকৃত সেবায় এটা বাতিল হয়েছে।"],
    ["Tax invoice", "কর চালানপত্র", "An invoice that meets VAT law requirements. In Bangladesh that's Mushak 6.3.", "VAT আইনের শর্ত পূরণ করা ইনভয়েস। বাংলাদেশে এটাই মূসক ৬.৩।", "/lab/0018-mushak-63-odoo-bangladesh"],
    ["Tax grid / tax report line", "ট্যাক্স গ্রিড", "Odoo tags on tax lines that map amounts to return boxes.", "ট্যাক্স লাইনে Odoo-র ট্যাগ, যা অঙ্কগুলো রিটার্নের ঘরে বসায়।"],
    ["Return deadline", "রিটার্নের শেষ তারিখ", "Under the Finance Act 2026, VAT returns are due within 15 days after each three-month cycle.", "অর্থ আইন ২০২৬ অনুযায়ী প্রতি তিন মাসের চক্র শেষের ১৫ দিনের মধ্যে VAT রিটার্ন জমা দিতে হবে।", "/compliance-watch/"],
    ["Credit carry-forward", "রেয়াত পরবর্তী মেয়াদে নেওয়া", "Unused input VAT credit carried to later tax periods.", "অব্যবহৃত উপকরণ কর রেয়াত পরের করমেয়াদে নিয়ে যাওয়া।"]
  ]
};
