// Glossary — Customs, trade & export finance.
module.exports = {
  id: "trade", en: "Customs, trade & LC", bn: "কাস্টমস, বাণিজ্য ও LC",
  terms: [
    ["HS code", "HS কোড", "The Harmonized System code that classifies goods for customs duty.", "শুল্কের জন্য পণ্য শ্রেণিবিন্যাসের হারমোনাইজড সিস্টেম কোড।", "/lab/0019-hs-code-customs-odoo-bangladesh"],
    ["Customs tariff", "কাস্টমস ট্যারিফ", "The schedule of duty rates by HS code.", "HS কোড অনুযায়ী শুল্ক হারের তালিকা।"],
    ["Assessable value (AV)", "শুল্কায়নযোগ্য মূল্য", "CIF value plus the 1% landing charge. It's the base for customs duties.", "CIF মূল্য, সঙ্গে ১% ল্যান্ডিং চার্জ। শুল্ক হিসাবের ভিত্তি এটাই।", "/tools/import-duty-calculator/"],
    ["Landing charge", "ল্যান্ডিং চার্জ", "1% of CIF added to reach the assessable value.", "শুল্কায়নযোগ্য মূল্য পেতে CIF-এর সঙ্গে যোগ করা ১%।", "/tools/import-duty-calculator/"],
    ["CD (Customs Duty)", "কাস্টমস ডিউটি", "The basic import duty, in slabs of 0, 1, 5, 10, 15 and 25%.", "মূল আমদানি শুল্ক, ০, ১, ৫, ১০, ১৫ আর ২৫% স্তরে।", "/tools/import-duty-calculator/"],
    ["RD (Regulatory Duty)", "রেগুলেটরি ডিউটি", "An additional duty on the assessable value, set each budget.", "শুল্কায়নযোগ্য মূল্যের ওপর বাড়তি শুল্ক, প্রতি বাজেটে নির্ধারিত।", "/tools/import-duty-calculator/"],
    ["AT (Advance Tax)", "অগ্রিম কর", "A VAT-law tax collected at import (7.5% for commercial importers). It's creditable in the VAT return.", "আমদানিতে আদায় করা VAT আইনের কর (বাণিজ্যিক আমদানিকারকের ৭.৫%)। VAT রিটার্নে রেয়াতযোগ্য।", "/tools/import-duty-calculator/"],
    ["TTI (Total Tax Incidence)", "মোট কর ভার", "All import taxes as a percentage of assessable value.", "শুল্কায়নযোগ্য মূল্যের শতাংশ হিসেবে সব আমদানি কর।", "/tools/import-duty-calculator/"],
    ["Bill of Entry (BoE)", "বিল অব এন্ট্রি", "The customs declaration for imported goods.", "আমদানি পণ্যের কাস্টমস ঘোষণাপত্র।"],
    ["Bill of Export", "বিল অব এক্সপোর্ট", "The customs declaration for exported goods.", "রপ্তানি পণ্যের কাস্টমস ঘোষণাপত্র।"],
    ["ASYCUDA World", "ASYCUDA ওয়ার্ল্ড", "The customs automation system used by Bangladesh Customs.", "বাংলাদেশ কাস্টমসের ব্যবহৃত স্বয়ংক্রিয় শুল্ক ব্যবস্থা।"],
    ["Bill of Lading (B/L)", "বিল অব লেডিং", "The shipping document that serves as receipt and title for goods shipped by sea.", "সমুদ্রপথে পাঠানো মালের রসিদ আর মালিকানার দলিল হিসেবে ব্যবহৃত শিপিং ডকুমেন্ট।"],
    ["Airway bill (AWB)", "এয়ারওয়ে বিল", "The transport document for air shipments.", "আকাশপথে পাঠানো চালানের পরিবহন ডকুমেন্ট।"],
    ["Commercial invoice", "বাণিজ্যিক ইনভয়েস", "The seller's invoice for exported goods, used by customs and banks.", "রপ্তানি পণ্যের বিক্রেতার ইনভয়েস, যা কাস্টমস আর ব্যাংক ব্যবহার করে।"],
    ["Packing list", "প্যাকিং লিস্ট", "A document listing the contents, weights and dimensions of each package.", "প্রতিটি প্যাকেজের ভেতরের জিনিস, ওজন আর মাপের তালিকা।"],
    ["Certificate of origin", "উৎপত্তি সনদ", "A document certifying the country where goods were made.", "পণ্য কোন দেশে তৈরি তা প্রত্যয়নকারী ডকুমেন্ট।"],
    ["GSP", "GSP", "The Generalised System of Preferences: duty-free or reduced access to markets such as the EU.", "অগ্রাধিকারমূলক বাজার-সুবিধা: EU-র মতো বাজারে শুল্কমুক্ত বা কম শুল্কে প্রবেশ।"],
    ["LDC graduation", "LDC থেকে উত্তরণ", "Bangladesh's move out of Least Developed Country status, which affects trade preferences.", "স্বল্পোন্নত দেশের তালিকা থেকে বাংলাদেশের উত্তরণ, যা বাণিজ্য-সুবিধায় প্রভাব ফেলে।"],
    ["LC (Letter of Credit)", "ঋণপত্র (LC)", "A bank's guarantee to pay the seller once compliant documents are presented.", "সঠিক ডকুমেন্ট জমা দিলে বিক্রেতাকে টাকা দেওয়ার ব্যাংকের নিশ্চয়তা।", "/lab/0020-lc-management-odoo-bangladesh"],
    ["Back-to-back LC (BBLC)", "ব্যাক-টু-ব্যাক LC", "An import LC opened against an export LC, typical in RMG for raw materials.", "রপ্তানি LC-র বিপরীতে খোলা আমদানি LC, কাঁচামালের জন্য RMG-তে প্রচলিত।", "/lab/0020-lc-management-odoo-bangladesh"],
    ["Master LC", "মাস্টার LC", "The export LC received from the buyer.", "বায়ারের কাছ থেকে পাওয়া রপ্তানি LC।"],
    ["Sales contract", "সেলস কন্ট্রাক্ট", "An export contract used instead of an LC, often with later payment terms.", "LC-র বদলে ব্যবহৃত রপ্তানি চুক্তি, প্রায়ই পরে পেমেন্টের শর্তে।"],
    ["UPAS / deferred LC", "UPAS / ডেফার্ড LC", "LCs where payment is made at a later date after acceptance.", "যে LC-তে গ্রহণের পর পরবর্তী তারিখে পেমেন্ট হয়।"],
    ["Sight LC", "সাইট LC", "An LC paid on presentation of compliant documents.", "সঠিক ডকুমেন্ট দেখানো মাত্র পরিশোধযোগ্য LC।"],
    ["LC amendment", "LC সংশোধন", "A change to an LC's terms, such as amount, date or shipment details.", "LC-র শর্তে পরিবর্তন, যেমন অঙ্ক, তারিখ বা শিপমেন্টের তথ্য।"],
    ["Discrepancy", "অসঙ্গতি", "A mismatch between documents and LC terms that can delay payment.", "ডকুমেন্ট আর LC-র শর্তের অমিল, যা পেমেন্ট আটকে দিতে পারে।"],
    ["Acceptance", "গ্রহণ (অ্যাকসেপট্যান্স)", "The buyer's bank agreeing to pay on the maturity date.", "মেয়াদপূর্তির দিনে পরিশোধে বায়ারের ব্যাংকের সম্মতি।"],
    ["Export proceeds realisation", "রপ্তানি আয় প্রত্যাবাসন", "Receipt of export payment in Bangladesh, which must happen within Bangladesh Bank's time limits.", "বাংলাদেশে রপ্তানির টাকা আসা, যা বাংলাদেশ ব্যাংকের সময়সীমার মধ্যে হতে হয়।", "/lab/0072-bangladesh-bank-import-lc-forex-odoo"],
    ["EXP form", "EXP ফর্ম", "The Bangladesh Bank export form that tracks each shipment until proceeds arrive.", "বাংলাদেশ ব্যাংকের রপ্তানি ফর্ম, যা টাকা না আসা পর্যন্ত প্রতিটি চালান ট্র্যাক করে।"],
    ["ERQ account", "ERQ অ্যাকাউন্ট", "Exporter's Retention Quota account for holding part of export earnings in foreign currency.", "রপ্তানি আয়ের একটা অংশ বৈদেশিক মুদ্রায় রাখার এক্সপোর্টার্স রিটেনশন কোটা অ্যাকাউন্ট।"],
    ["EDF", "রপ্তানি উন্নয়ন তহবিল", "The Export Development Fund, a Bangladesh Bank refinancing scheme for input imports.", "উপকরণ আমদানির জন্য বাংলাদেশ ব্যাংকের পুনঃঅর্থায়ন তহবিল।"],
    ["FX (foreign exchange) rate", "বৈদেশিক মুদ্রার বিনিময় হার", "The BDT rate used for customs, bank settlement or accounting.", "কাস্টমস, ব্যাংক নিষ্পত্তি বা হিসাবে ব্যবহৃত টাকার হার।", "/lab/0072-bangladesh-bank-import-lc-forex-odoo"],
    ["Bonded warehouse", "বন্ডেড ওয়্যারহাউস", "A licensed store where imported inputs for export production are held duty-free.", "লাইসেন্সপ্রাপ্ত গুদাম, যেখানে রপ্তানি উৎপাদনের আমদানি উপকরণ শুল্কমুক্ত রাখা হয়।", "/lab/0073-bonded-warehouse-management-odoo-bangladesh"],
    ["Customs bond licence", "কাস্টমস বন্ড লাইসেন্স", "Permission to import inputs duty-free under bond for export.", "রপ্তানির জন্য বন্ডে শুল্কমুক্ত উপকরণ আমদানির অনুমতি।", "/lab/0073-bonded-warehouse-management-odoo-bangladesh"],
    ["UD (Utilisation Declaration)", "ইউটিলাইজেশন ডিক্লারেশন", "The approval, issued via BGMEA/BKMEA, to use bonded inputs against an export order.", "BGMEA/BKMEA-র মাধ্যমে দেওয়া অনুমোদন, যাতে রপ্তানি অর্ডারের বিপরীতে বন্ডেড উপকরণ ব্যবহার করা যায়।"],
    ["UP (Utilisation Permission)", "ইউটিলাইজেশন পারমিশন", "The EPZ equivalent permission for using imported inputs.", "আমদানি উপকরণ ব্যবহারের EPZ-এর সমতুল্য অনুমতি।", "/lab/0021-epz-sez-compliance-odoo-bangladesh"],
    ["Passbook (bond)", "বন্ড পাসবুক", "The register of bonded imports and consumption against exports.", "বন্ডে আমদানি আর রপ্তানির বিপরীতে ব্যবহারের রেজিস্টার।"],
    ["Duty drawback", "শুল্ক প্রত্যর্পণ", "A refund of duties paid on inputs used in exported goods.", "রপ্তানি পণ্যে ব্যবহৃত উপকরণের শুল্ক ফেরত।", "/lab/0041-odoo-landed-costs-duty-drawback-bangladesh"],
    ["Cash incentive / subsidy", "নগদ প্রণোদনা", "Government export incentives paid as a percentage of export value. WHT on it is now 5%.", "রপ্তানি মূল্যের শতাংশ হিসেবে দেওয়া সরকারি প্রণোদনা। এর ওপর উৎসে কর এখন ৫%।", "/compliance-watch/"],
    ["EPZ", "রপ্তানি প্রক্রিয়াকরণ অঞ্চল", "Export Processing Zones run by BEPZA, with their own customs and labour rules.", "BEPZA পরিচালিত রপ্তানি প্রক্রিয়াকরণ অঞ্চল, যার নিজস্ব শুল্ক আর শ্রম নিয়ম আছে।", "/lab/0021-epz-sez-compliance-odoo-bangladesh"],
    ["SEZ / economic zone", "বিশেষ অর্থনৈতিক অঞ্চল", "Economic zones under BEZA with incentive packages.", "প্রণোদনা প্যাকেজসহ BEZA-র অধীন অর্থনৈতিক অঞ্চল।", "/lab/0021-epz-sez-compliance-odoo-bangladesh"],
    ["Deemed exporter", "প্রচ্ছন্ন রপ্তানিকারক", "A local supplier to exporters treated like an exporter for some incentives.", "রপ্তানিকারকের স্থানীয় সরবরাহকারী, যাকে কিছু প্রণোদনায় রপ্তানিকারকের মতো ধরা হয়।"],
    ["IRC / ERC", "আমদানি / রপ্তানি নিবন্ধন সনদ", "Import and Export Registration Certificates, required to trade internationally.", "আন্তর্জাতিক বাণিজ্যের জন্য আবশ্যক আমদানি ও রপ্তানি নিবন্ধন সনদ।"],
    ["LCA form / IMP form", "LCA / IMP ফর্ম", "Bangladesh Bank forms for opening import LCs and reporting import payments.", "আমদানি LC খোলা আর আমদানি পেমেন্ট রিপোর্টের বাংলাদেশ ব্যাংকের ফর্ম।"],
    ["Shipping bill / guarantee", "শিপিং গ্যারান্টি", "A bank guarantee to release goods before original documents arrive.", "মূল ডকুমেন্ট আসার আগে মাল ছাড়াতে ব্যাংকের গ্যারান্টি।"],
    ["Port charges", "বন্দর চার্জ", "Fees charged by Chattogram/Mongla ports and berth operators.", "চট্টগ্রাম/মোংলা বন্দর আর বার্থ অপারেটরের চার্জ।"],
    ["Transshipment", "ট্রান্সশিপমেন্ট", "Moving cargo between vessels at an intermediate port.", "মধ্যবর্তী বন্দরে এক জাহাজ থেকে আরেক জাহাজে মাল স্থানান্তর।"],
    ["EUDR", "EU বন উজাড় বিধিমালা", "The EU Deforestation Regulation, which requires origin data for wood, rubber and other commodities.", "EU-র বন উজাড় বিধিমালা, যাতে কাঠ, রাবার আর অন্যান্য পণ্যের উৎসের ডেটা লাগে।", "/lab/0079-eudr-odoo-traceability-rubber-wood-furniture-bangladesh"],
    ["Buyer compliance audit", "বায়ারের কমপ্লায়েন্স অডিট", "Social, environmental and quality audits by brands or third parties.", "ব্র্যান্ড বা তৃতীয় পক্ষের সামাজিক, পরিবেশগত আর মানের অডিট।", "/lab/0075-esg-sustainability-reporting-odoo-rmg-bangladesh"],
    ["ESG reporting", "ESG রিপোর্টিং", "Reporting on environmental, social and governance performance, increasingly demanded by buyers.", "পরিবেশ, সামাজিক আর সুশাসন বিষয়ক প্রতিবেদন, যা বায়াররা ক্রমশ বেশি চাইছে।", "/lab/0075-esg-sustainability-reporting-odoo-rmg-bangladesh"],
    ["BEPZA", "বেপজা", "Bangladesh Export Processing Zones Authority, which runs the EPZs.", "বাংলাদেশ রপ্তানি প্রক্রিয়াকরণ এলাকা কর্তৃপক্ষ, যা EPZ পরিচালনা করে।", "/lab/0021-epz-sez-compliance-odoo-bangladesh"],
    ["BEZA", "বেজা", "Bangladesh Economic Zones Authority, which runs the economic zones.", "বাংলাদেশ অর্থনৈতিক অঞ্চল কর্তৃপক্ষ, যা অর্থনৈতিক অঞ্চল পরিচালনা করে।"],
    ["Bangladesh Bank", "বাংলাদেশ ব্যাংক", "The central bank, which sets foreign-exchange and LC rules.", "কেন্দ্রীয় ব্যাংক, যা বৈদেশিক মুদ্রা আর LC-র নিয়ম ঠিক করে।", "/lab/0072-bangladesh-bank-import-lc-forex-odoo"]
  ]
};
