// Industry hubs — /industries/<slug>/ and /bn/industries/<slug>/.
// est: preset industry key for the Odoo Cost Estimator (?ind=...).
// articles: Lab slugs (titles are pulled from labIndex at build time).
// tools: tool slugs under /tools/.
module.exports = [
  {
    slug: "rmg-garments", est: "rmg_garments", tag: "Export · Labour-intensive", tagBn: "রপ্তানি · শ্রমঘন",
    en: { name: "RMG & Garments", short: "Style/size/colour variants, subcontracting, wage-board payroll, LC and buyer compliance.",
      pains: ["Thousands of SKUs from style × colour × size, with costing done per style in Excel", "Job-work and subcontracting (printing, embroidery, washing) with material sent out and never reconciled", "Worker payroll for thousands of people on wage-board grades, OT and attendance bonuses", "Back-to-back LCs, bonded raw material and buyer audit requests for traceability and ESG data"],
      modules: ["Manufacturing (MRP) with variants", "Inventory with lots", "Purchase", "Subcontracting", "Payroll + Attendance", "Accounting (multi-currency)", "Quality"] },
    bn: { name: "RMG ও গার্মেন্টস", short: "স্টাইল/সাইজ/রঙের ভ্যারিয়েন্ট, সাবকন্ট্র্যাক্টিং, ওয়েজ বোর্ডের পে-রোল, LC আর বায়ারের কমপ্লায়েন্স।",
      pains: ["স্টাইল × রঙ × সাইজে হাজারো SKU, আর প্রতিটা স্টাইলের কস্টিং হয় Excel-এ", "প্রিন্টিং, এমব্রয়ডারি, ওয়াশিংয়ের মতো জব-ওয়ার্ক আর সাবকন্ট্র্যাক্টিংয়ে ম্যাটেরিয়াল বাইরে যায়, কিন্তু কখনো মেলানো হয় না", "হাজারো শ্রমিকের পে-রোল: ওয়েজ বোর্ডের গ্রেড, OT আর হাজিরা বোনাস", "ব্যাক-টু-ব্যাক LC, বন্ডেড কাঁচামাল, আর ট্রেসেবিলিটি ও ESG ডেটা নিয়ে বায়ারের অডিট"],
      modules: ["ভ্যারিয়েন্টসহ Manufacturing (MRP)", "লটসহ Inventory", "Purchase", "সাবকন্ট্র্যাক্টিং", "Payroll ও Attendance", "Accounting (মাল্টি-কারেন্সি)", "Quality"] },
    compliance: ["wage", "lc", "bond", "vat", "esg"],
    articles: ["0033-odoo-rmg-garments-bangladesh", "0063-odoo-subcontracting-rmg-garments-bangladesh", "0022-bgmea-wage-board-odoo-payroll", "0020-lc-management-odoo-bangladesh", "0073-bonded-warehouse-management-odoo-bangladesh", "0075-esg-sustainability-reporting-odoo-rmg-bangladesh", "0021-epz-sez-compliance-odoo-bangladesh"],
    tools: ["rmg-wage-calculator", "odoo-cost-estimator", "import-duty-calculator"]
  },
  {
    slug: "textile-spinning", est: "textile", tag: "Process manufacturing", tagBn: "প্রসেস ম্যানুফ্যাকচারিং",
    en: { name: "Textile, Spinning & Weaving", short: "Yarn counts, lots and shades, process losses, bonded cotton and export LCs.",
      pains: ["Yield and process loss across blow room, carding and spinning, tracked on paper", "Lot and shade consistency for dyeing, and buyers rejecting mixed lots", "Imported cotton under bond, with consumption to justify to customs", "Power and machine downtime driving cost with no data behind it"],
      modules: ["Manufacturing with by-products", "Inventory (lots)", "Quality", "Maintenance", "Purchase", "Accounting"] },
    bn: { name: "টেক্সটাইল, স্পিনিং ও উইভিং", short: "সুতার কাউন্ট, লট আর শেড, প্রসেস লস, বন্ডেড তুলা আর রপ্তানি LC।",
      pains: ["ব্লো রুম, কার্ডিং আর স্পিনিংয়ে ইল্ড আর প্রসেস লস কাগজে হিসাব হয়", "ডাইংয়ে লট আর শেডের মিল না থাকা, আর মিশ্র লটের জন্য বায়ারের রিজেকশন", "বন্ডে আমদানি করা তুলা, যার কনজাম্পশন কাস্টমসকে দেখাতে হয়", "বিদ্যুৎ আর মেশিন বন্ধ থাকায় খরচ বাড়ে, অথচ এর কোনো ডেটা নেই"],
      modules: ["বাই-প্রোডাক্টসহ Manufacturing", "Inventory (লট)", "Quality", "Maintenance", "Purchase", "Accounting"] },
    compliance: ["bond", "lc", "vat"],
    articles: ["0037-odoo-spinning-mill-bangladesh", "0040-odoo-quality-control-iso-bangladesh", "0061-odoo-preventive-maintenance-bangladesh", "0073-bonded-warehouse-management-odoo-bangladesh", "0038-odoo-manufacturing-routing-bangladesh"],
    tools: ["odoo-cost-estimator", "import-duty-calculator", "vat-mushak-helper"]
  },
  {
    slug: "pharma", est: "pharma", tag: "Regulated", tagBn: "নিয়ন্ত্রিত খাত",
    en: { name: "Pharmaceuticals", short: "Batch traceability, expiry, QC release, DGDA records and API imports.",
      pains: ["Full batch genealogy from API lot to finished pack, demanded in recalls and audits", "FEFO picking and expiry write-offs across depots and distributors", "QC hold and release before stock can be sold", "Imported APIs with duty exemptions that change every budget"],
      modules: ["Manufacturing", "Inventory (lots + expiry)", "Quality", "PLM", "Purchase", "Sales + distributor pricing", "Accounting"] },
    bn: { name: "ফার্মাসিউটিক্যালস", short: "ব্যাচ ট্রেসেবিলিটি, মেয়াদ, QC রিলিজ, DGDA-র রেকর্ড আর API আমদানি।",
      pains: ["API লট থেকে ফিনিশড প্যাক পর্যন্ত পুরো ব্যাচের ইতিহাস, যা রিকল আর অডিটে চাওয়া হয়", "ডিপো আর ডিস্ট্রিবিউটর জুড়ে FEFO পিকিং আর মেয়াদোত্তীর্ণ পণ্যের রাইট-অফ", "বিক্রির আগে QC হোল্ড আর রিলিজ", "আমদানি করা API-র শুল্ক অব্যাহতি, যা প্রতি বাজেটে বদলায়"],
      modules: ["Manufacturing", "Inventory (লট ও মেয়াদ)", "Quality", "PLM", "Purchase", "Sales ও ডিস্ট্রিবিউটর প্রাইসিং", "Accounting"] },
    compliance: ["vat", "duty"],
    articles: ["0035-odoo-pharma-bangladesh", "0040-odoo-quality-control-iso-bangladesh", "0041-odoo-landed-costs-duty-drawback-bangladesh", "0065-odoo-barcode-warehouse-scanning-bangladesh"],
    tools: ["odoo-cost-estimator", "import-duty-calculator", "vat-mushak-helper"]
  },
  {
    slug: "trading-distribution", est: "trading", tag: "Import · Distribution", tagBn: "আমদানি · বিতরণ",
    en: { name: "Trading & Distribution", short: "Multi-warehouse stock, landed costs, dealer credit, Mushak 6.2.1 and the new 9.1.1 return.",
      pains: ["Stock spread across warehouses and depots, with numbers nobody trusts", "Landed cost per shipment calculated in Excel, so margins are guesses", "Dealer credit limits and collections tracked by salespeople's memory", "Trader VAT: the purchase-sales register and the new Mushak 9.1.1 return"],
      modules: ["Inventory (multi-warehouse)", "Purchase + landed costs", "Sales", "Accounting", "Barcode"] },
    bn: { name: "ট্রেডিং ও ডিস্ট্রিবিউশন", short: "একাধিক ওয়্যারহাউসের স্টক, ল্যান্ডেড কস্ট, ডিলার ক্রেডিট, Mushak 6.2.1 আর নতুন 9.1.1 রিটার্ন।",
      pains: ["ওয়্যারহাউস আর ডিপো জুড়ে স্টক ছড়ানো, অথচ হিসাবে কেউ ভরসা করে না", "প্রতিটি চালানের ল্যান্ডেড কস্ট Excel-এ হিসাব হয়, তাই মার্জিন আন্দাজে চলে", "ডিলারের ক্রেডিট লিমিট আর আদায় সেলসম্যানের স্মৃতিনির্ভর", "ব্যবসায়ীর VAT: ক্রয়-বিক্রয় হিসাব পুস্তক আর নতুন Mushak 9.1.1 রিটার্ন"],
      modules: ["Inventory (মাল্টি-ওয়্যারহাউস)", "Purchase ও ল্যান্ডেড কস্ট", "Sales", "Accounting", "Barcode"] },
    compliance: ["vat", "duty", "tds"],
    articles: ["0036-odoo-trading-company-bangladesh", "0041-odoo-landed-costs-duty-drawback-bangladesh", "0065-odoo-barcode-warehouse-scanning-bangladesh", "0039-odoo-reordering-rules-mto-bangladesh", "0072-bangladesh-bank-import-lc-forex-odoo"],
    tools: ["import-duty-calculator", "vat-mushak-helper", "odoo-cost-estimator"]
  },
  {
    slug: "cycle-light-engineering", est: "cycle_export", tag: "Export · Assembly", tagBn: "রপ্তানি · অ্যাসেম্বলি",
    en: { name: "Bicycle & Light-Engineering Export", short: "Deep BOMs, imported components, duty drawback and EU buyer documentation.",
      pains: ["Multi-level BOMs with hundreds of imported components per model", "Duty drawback and bonded components needing consumption proof", "EU buyers asking for origin and traceability documentation", "Production planning across frame, paint and assembly lines"],
      modules: ["Manufacturing (multi-level BOM)", "Inventory", "Purchase", "PLM", "Quality", "Accounting (multi-currency)"] },
    bn: { name: "বাইসাইকেল ও লাইট-ইঞ্জিনিয়ারিং রপ্তানি", short: "গভীর BOM, আমদানি করা কম্পোনেন্ট, ডিউটি ড্রব্যাক আর EU বায়ারের ডকুমেন্টেশন।",
      pains: ["প্রতিটি মডেলে শত শত আমদানি করা কম্পোনেন্টসহ মাল্টি-লেভেল BOM", "ডিউটি ড্রব্যাক আর বন্ডেড কম্পোনেন্ট, যার কনজাম্পশনের প্রমাণ লাগে", "EU বায়ারের কাছ থেকে অরিজিন আর ট্রেসেবিলিটির কাগজের চাহিদা", "ফ্রেম, পেইন্ট আর অ্যাসেম্বলি লাইনে প্রোডাকশন প্ল্যানিং"],
      modules: ["Manufacturing (মাল্টি-লেভেল BOM)", "Inventory", "Purchase", "PLM", "Quality", "Accounting (মাল্টি-কারেন্সি)"] },
    compliance: ["bond", "lc", "duty"],
    articles: ["0034-odoo-cycle-export-bangladesh", "0041-odoo-landed-costs-duty-drawback-bangladesh", "0019-hs-code-customs-odoo-bangladesh", "0038-odoo-manufacturing-routing-bangladesh"],
    tools: ["odoo-cost-estimator", "import-duty-calculator"]
  },
  {
    slug: "leather-footwear", est: "manufacturing", tag: "Export · Manufacturing", tagBn: "রপ্তানি · ম্যানুফ্যাকচারিং",
    en: { name: "Leather & Footwear", short: "Hide grading and yield, size runs, bonded chemicals and export compliance.",
      pains: ["Yield from hides varies by grade, which breaks standard costing", "Size-run production and last/mould tracking", "Bonded chemicals and imported components", "Buyer compliance (LWG, chemical restrictions) needing batch data"],
      modules: ["Manufacturing", "Inventory (lots)", "Quality", "Purchase", "Accounting"] },
    bn: { name: "চামড়া ও জুতা", short: "চামড়ার গ্রেড ও ইল্ড, সাইজ রান, বন্ডেড কেমিক্যাল আর রপ্তানি কমপ্লায়েন্স।",
      pains: ["চামড়ার গ্রেড অনুযায়ী ইল্ড বদলায়, ফলে স্ট্যান্ডার্ড কস্টিং ভেঙে পড়ে", "সাইজ-রান প্রোডাকশন আর লাস্ট/মোল্ড ট্র্যাকিং", "বন্ডেড কেমিক্যাল আর আমদানি করা কম্পোনেন্ট", "বায়ারের কমপ্লায়েন্স (LWG, কেমিক্যাল বিধিনিষেধ), যার জন্য ব্যাচের ডেটা লাগে"],
      modules: ["Manufacturing", "Inventory (লট)", "Quality", "Purchase", "Accounting"] },
    compliance: ["bond", "lc", "vat"],
    articles: ["0066-odoo-leather-footwear-manufacturing-bangladesh", "0073-bonded-warehouse-management-odoo-bangladesh", "0040-odoo-quality-control-iso-bangladesh"],
    tools: ["odoo-cost-estimator", "import-duty-calculator"]
  },
  {
    slug: "jute", est: "manufacturing", tag: "Export · Agro-industrial", tagBn: "রপ্তানি · কৃষিশিল্প",
    en: { name: "Jute & Jute-Diversified Products", short: "Raw jute grading and moisture, seasonal buying, and export of yarn, sacking and JDPs.",
      pains: ["Raw jute bought seasonally by grade and moisture, with weight loss in storage", "Mills producing yarn, hessian and sacking with by-products", "Export incentives and cash subsidy (WHT on subsidies now 5%)", "Diversified products with small runs and many SKUs"],
      modules: ["Purchase", "Inventory (lots)", "Manufacturing", "Quality", "Accounting"] },
    bn: { name: "পাট ও পাটজাত বহুমুখী পণ্য", short: "কাঁচা পাটের গ্রেড ও আর্দ্রতা, মৌসুমি ক্রয়, আর সুতা, বস্তা ও JDP রপ্তানি।",
      pains: ["গ্রেড আর আর্দ্রতা দেখে মৌসুমে কাঁচা পাট কেনা, আর গুদামে ওজন কমে যাওয়া", "সুতা, হেসিয়ান আর বস্তা তৈরিতে বাই-প্রোডাক্টসহ মিল", "রপ্তানি প্রণোদনা আর নগদ সহায়তা (সহায়তার ওপর উৎসে কর এখন ৫%)", "অল্প পরিমাণে অনেক SKU-র বহুমুখী পণ্য"],
      modules: ["Purchase", "Inventory (লট)", "Manufacturing", "Quality", "Accounting"] },
    compliance: ["lc", "vat", "tds"],
    articles: ["0067-odoo-jute-products-bangladesh", "0020-lc-management-odoo-bangladesh"],
    tools: ["odoo-cost-estimator", "vat-mushak-helper"]
  },
  {
    slug: "plastics-packaging", est: "manufacturing", tag: "Manufacturing", tagBn: "ম্যানুফ্যাকচারিং",
    en: { name: "Plastics & Packaging", short: "Resin imports, regrind and scrap, mould tracking and machine utilisation.",
      pains: ["Imported resin priced in USD, with landed cost swinging every shipment", "Regrind, scrap and recycled content affecting cost and quality", "Mould changeovers and machine utilisation", "Customer-specific printing and cartons in small runs"],
      modules: ["Manufacturing (work centres)", "Inventory", "Purchase + landed costs", "Maintenance", "Quality"] },
    bn: { name: "প্লাস্টিক ও প্যাকেজিং", short: "রেজিন আমদানি, রিগ্রাইন্ড ও স্ক্র্যাপ, মোল্ড ট্র্যাকিং আর মেশিনের ব্যবহার।",
      pains: ["USD-তে কেনা আমদানি করা রেজিন, যার ল্যান্ডেড কস্ট প্রতি চালানে ওঠানামা করে", "রিগ্রাইন্ড, স্ক্র্যাপ আর রিসাইকেল্ড উপাদান, যা খরচ আর মান দুটোই বদলায়", "মোল্ড বদল আর মেশিনের ব্যবহার", "কাস্টমারভিত্তিক প্রিন্টিং আর কার্টন, অল্প পরিমাণে"],
      modules: ["Manufacturing (ওয়ার্ক সেন্টার)", "Inventory", "Purchase ও ল্যান্ডেড কস্ট", "Maintenance", "Quality"] },
    compliance: ["duty", "vat", "tds"],
    articles: ["0068-odoo-plastics-packaging-manufacturing-bangladesh", "0041-odoo-landed-costs-duty-drawback-bangladesh", "0061-odoo-preventive-maintenance-bangladesh"],
    tools: ["import-duty-calculator", "odoo-cost-estimator"]
  },
  {
    slug: "food-beverage", est: "manufacturing", tag: "FMCG · Agro-processing", tagBn: "FMCG · কৃষি প্রক্রিয়াজাতকরণ",
    en: { name: "Food, Beverage & Agro-Processing", short: "Batch and expiry, BSTI, distributor networks, and the new 0.2% advance tax on retail supplies.",
      pains: ["Batch, expiry and FEFO across depots and distributor stock", "Recipe costing with volatile agricultural inputs", "Distributor schemes, secondary sales and damage returns", "SD and VAT on beverages, and the new 0.2% advance tax on collections from retailers"],
      modules: ["Manufacturing (recipes)", "Inventory (lots + expiry)", "Sales + distributor pricing", "Quality", "Accounting"] },
    bn: { name: "খাদ্য, পানীয় ও কৃষি প্রক্রিয়াজাতকরণ", short: "ব্যাচ ও মেয়াদ, BSTI, ডিস্ট্রিবিউটর নেটওয়ার্ক, আর খুচরা সরবরাহে নতুন ০.২% অগ্রিম কর।",
      pains: ["ডিপো আর ডিস্ট্রিবিউটরের স্টকে ব্যাচ, মেয়াদ আর FEFO", "ওঠানামা করা কৃষি উপকরণে রেসিপির কস্টিং", "ডিস্ট্রিবিউটর স্কিম, সেকেন্ডারি সেলস আর ড্যামেজ রিটার্ন", "পানীয়তে SD ও VAT, আর খুচরা বিক্রেতার কাছ থেকে আদায়ে নতুন ০.২% অগ্রিম কর"],
      modules: ["Manufacturing (রেসিপি)", "Inventory (লট ও মেয়াদ)", "Sales ও ডিস্ট্রিবিউটর প্রাইসিং", "Quality", "Accounting"] },
    compliance: ["vat", "tds"],
    articles: ["0069-odoo-food-beverage-agro-processing-bangladesh", "0040-odoo-quality-control-iso-bangladesh", "0039-odoo-reordering-rules-mto-bangladesh"],
    tools: ["vat-mushak-helper", "odoo-cost-estimator"]
  },
  {
    slug: "ceramics-tiles", est: "manufacturing", tag: "Manufacturing", tagBn: "ম্যানুফ্যাকচারিং",
    en: { name: "Ceramics & Tiles", short: "Grades and shades from one batch, kiln costs, breakage and dealer networks.",
      pains: ["One production batch yielding several grades and shade lots", "Gas and kiln energy as a major cost driver", "Breakage in handling and transit", "Dealer and project sales with credit and delivery scheduling"],
      modules: ["Manufacturing (by-products)", "Inventory (lots)", "Sales", "Quality", "Accounting"] },
    bn: { name: "সিরামিক ও টাইলস", short: "এক ব্যাচ থেকে একাধিক গ্রেড ও শেড, কিলনের খরচ, ভাঙন আর ডিলার নেটওয়ার্ক।",
      pains: ["এক প্রোডাকশন ব্যাচ থেকে কয়েকটি গ্রেড আর শেড লট", "গ্যাস আর কিলনের জ্বালানি খরচের বড় অংশ", "হ্যান্ডলিং আর পরিবহনে ভাঙন", "ক্রেডিট আর ডেলিভারি শিডিউলসহ ডিলার ও প্রজেক্ট বিক্রি"],
      modules: ["Manufacturing (বাই-প্রোডাক্ট)", "Inventory (লট)", "Sales", "Quality", "Accounting"] },
    compliance: ["vat", "duty"],
    articles: ["0083-odoo-ceramics-tiles-manufacturing-bangladesh", "0040-odoo-quality-control-iso-bangladesh"],
    tools: ["odoo-cost-estimator", "import-duty-calculator"]
  },
  {
    slug: "steel-light-engineering", est: "manufacturing", tag: "Heavy manufacturing", tagBn: "ভারী শিল্প",
    en: { name: "Steel Re-Rolling & Light Engineering", short: "Scrap to billet to MS product, fixed-rate VAT per tonne, and weighbridge data.",
      pains: ["Scrap → billet → rod with melting and rolling losses", "Fixed-base VAT per metric tonne (rates raised in the Finance Act 2026)", "Weighbridge readings keyed in by hand", "Job-shop fabrication with custom quotes"],
      modules: ["Manufacturing", "Inventory (weights, lots)", "IoT (weighbridge)", "Sales", "Accounting"] },
    bn: { name: "স্টিল রি-রোলিং ও লাইট ইঞ্জিনিয়ারিং", short: "স্ক্র্যাপ থেকে বিলেট থেকে MS পণ্য, প্রতি টনে নির্দিষ্ট হারে VAT, আর ওয়েব্রিজের ডেটা।",
      pains: ["গলানো আর রোলিংয়ের লসসহ স্ক্র্যাপ → বিলেট → রড", "প্রতি মেট্রিক টনে নির্দিষ্ট ভিত্তির VAT (অর্থ আইন ২০২৬-এ হার বেড়েছে)", "ওয়েব্রিজের রিডিং হাতে টাইপ করা", "কাস্টম কোটেশনে জব-শপ ফ্যাব্রিকেশন"],
      modules: ["Manufacturing", "Inventory (ওজন, লট)", "IoT (ওয়েব্রিজ)", "Sales", "Accounting"] },
    compliance: ["vat", "tds"],
    articles: ["0084-odoo-steel-rerolling-light-engineering-bangladesh", "0056-odoo-iot-box-bangladesh"],
    tools: ["vat-mushak-helper", "odoo-cost-estimator"]
  },
  {
    slug: "furniture", est: "manufacturing", tag: "Export · Made-to-order", tagBn: "রপ্তানি · অর্ডারভিত্তিক",
    en: { name: "Furniture Manufacturing & Export", short: "Made-to-order BOMs, timber traceability for EUDR, and showroom sales.",
      pains: ["Made-to-order products with configurable BOMs", "Timber and rubberwood origin data for the EU Deforestation Regulation", "Showroom and project sales alongside export orders", "Finishing and packing stages that hide WIP"],
      modules: ["Manufacturing", "Inventory (lots)", "Sales + configurator", "Purchase", "Accounting"] },
    bn: { name: "ফার্নিচার উৎপাদন ও রপ্তানি", short: "অর্ডারভিত্তিক BOM, EUDR-এর জন্য কাঠের ট্রেসেবিলিটি, আর শোরুমে বিক্রি।",
      pains: ["কনফিগার করা যায় এমন BOM-সহ অর্ডারভিত্তিক পণ্য", "EU বন উজাড় বিধিমালার (EUDR) জন্য কাঠ আর রাবার কাঠের উৎসের ডেটা", "রপ্তানি অর্ডারের পাশাপাশি শোরুম আর প্রজেক্ট বিক্রি", "ফিনিশিং আর প্যাকিং ধাপে WIP চোখের আড়ালে থাকে"],
      modules: ["Manufacturing", "Inventory (লট)", "Sales ও কনফিগারেটর", "Purchase", "Accounting"] },
    compliance: ["eudr", "vat", "lc"],
    articles: ["0085-odoo-furniture-manufacturing-export-bangladesh", "0079-eudr-odoo-traceability-rubber-wood-furniture-bangladesh"],
    tools: ["odoo-cost-estimator", "vat-mushak-helper"]
  },
  {
    slug: "tea-plantation", est: "manufacturing", tag: "Agriculture", tagBn: "কৃষি",
    en: { name: "Tea Estates & Plantations", short: "Garden-level plucking and yield, worker rations and wages, and auction sales.",
      pains: ["Daily plucking by section and worker, recorded in registers", "Worker wages, rations and welfare for resident labour", "Factory processing and grade outturn", "Auction-based sales at Chattogram"],
      modules: ["Project/field data (Studio)", "Payroll", "Manufacturing", "Inventory", "Accounting"] },
    bn: { name: "চা বাগান ও প্ল্যান্টেশন", short: "বাগানভিত্তিক পাতা তোলা ও ইল্ড, শ্রমিকের রেশন ও মজুরি, আর নিলামে বিক্রি।",
      pains: ["সেকশন আর শ্রমিক ধরে প্রতিদিনের পাতা তোলা, রেজিস্টারে লেখা", "বাগানে থাকা শ্রমিকদের মজুরি, রেশন আর কল্যাণ সুবিধা", "ফ্যাক্টরির প্রক্রিয়াজাতকরণ আর গ্রেডভিত্তিক আউটটার্ন", "চট্টগ্রামে নিলামভিত্তিক বিক্রি"],
      modules: ["প্রজেক্ট/মাঠের ডেটা (Studio)", "Payroll", "Manufacturing", "Inventory", "Accounting"] },
    compliance: ["vat", "tds"],
    articles: ["0086-odoo-tea-estate-plantation-management-bangladesh", "0093-odoo-studio-no-code-bangladesh"],
    tools: ["odoo-cost-estimator"]
  },
  {
    slug: "poultry-dairy", est: "manufacturing", tag: "Agribusiness", tagBn: "কৃষি ব্যবসা",
    en: { name: "Poultry, Dairy & Feed", short: "Flock and herd tracking, feed mills, milk collection and cold chain.",
      pains: ["Flock/herd records, mortality and feed conversion", "Feed mill production with commodity-priced inputs", "Milk collection from many small farmers with daily payments", "Cold chain and short shelf life in distribution"],
      modules: ["Manufacturing", "Inventory (lots + expiry)", "Purchase (farmer payments)", "Sales", "Accounting"] },
    bn: { name: "পোল্ট্রি, ডেইরি ও ফিড", short: "ফ্লক আর গবাদিপশুর ট্র্যাকিং, ফিড মিল, দুধ সংগ্রহ আর কোল্ড চেইন।",
      pains: ["ফ্লক/পশুর রেকর্ড, মৃত্যুহার আর ফিড কনভার্শন", "পণ্যবাজারের দামে কেনা উপকরণে ফিড মিলের উৎপাদন", "অনেক ছোট খামারির কাছ থেকে দুধ সংগ্রহ, প্রতিদিন পেমেন্ট", "বিতরণে কোল্ড চেইন আর অল্প মেয়াদ"],
      modules: ["Manufacturing", "Inventory (লট ও মেয়াদ)", "Purchase (খামারির পেমেন্ট)", "Sales", "Accounting"] },
    compliance: ["vat", "tds"],
    articles: ["0087-odoo-poultry-dairy-agribusiness-bangladesh"],
    tools: ["odoo-cost-estimator"]
  },
  {
    slug: "cold-storage-warehousing", est: "services", tag: "Agri logistics", tagBn: "কৃষি লজিস্টিকস",
    en: { name: "Cold Storage & Agri Warehousing", short: "Farmer receipts, rent per bag, loans against stock and seasonal release.",
      pains: ["Thousands of farmer receipts per season", "Rent per bag or per kg, and loans against stored produce", "Seasonal release schedules and chamber allocation", "Cash-heavy collections"],
      modules: ["Inventory (consignment / owner stock)", "Invoicing", "Accounting", "Studio"] },
    bn: { name: "কোল্ড স্টোরেজ ও কৃষি গুদাম", short: "খামারির রসিদ, বস্তাপ্রতি ভাড়া, মজুদের বিপরীতে ঋণ আর মৌসুমি ছাড়।",
      pains: ["প্রতি মৌসুমে হাজারো খামারির রসিদ", "বস্তা বা কেজিপ্রতি ভাড়া, আর মজুদ ফসলের বিপরীতে ঋণ", "মৌসুমি ছাড়ের সময়সূচি আর চেম্বার বরাদ্দ", "নগদনির্ভর আদায়"],
      modules: ["Inventory (কনসাইনমেন্ট / মালিকের স্টক)", "Invoicing", "Accounting", "Studio"] },
    compliance: ["vat"],
    articles: ["0088-odoo-cold-storage-potato-agri-warehousing-bangladesh"],
    tools: ["vat-mushak-helper", "odoo-cost-estimator"]
  },
  {
    slug: "freight-forwarding-cf", est: "services", tag: "Logistics", tagBn: "লজিস্টিকস",
    en: { name: "Freight Forwarding & C&F Agents", short: "Job costing per shipment, reimbursables, and the 1%-or-10% withholding on forwarders.",
      pains: ["Job-wise profitability across freight, duty and handling", "Reimbursable costs paid on clients' behalf", "Multi-currency invoices from shipping lines", "Withholding tax on forwarding agents: higher of 1% of gross bill or 10% of commission"],
      modules: ["Project / job costing", "Accounting (multi-currency)", "Invoicing", "Documents"] },
    bn: { name: "ফ্রেইট ফরোয়ার্ডিং ও C&F এজেন্ট", short: "প্রতিটি চালানের জব কস্টিং, রিইমবার্সেবল খরচ, আর ফরোয়ার্ডারের ওপর ১% বা ১০% উৎসে কর।",
      pains: ["ফ্রেইট, ডিউটি আর হ্যান্ডলিং মিলিয়ে জবভিত্তিক লাভ", "ক্লায়েন্টের হয়ে দেওয়া রিইমবার্সেবল খরচ", "শিপিং লাইনের মাল্টি-কারেন্সি ইনভয়েস", "ফরোয়ার্ডিং এজেন্টের উৎসে কর: মোট বিলের ১% বা কমিশনের ১০%, যেটা বেশি"],
      modules: ["প্রজেক্ট / জব কস্টিং", "Accounting (মাল্টি-কারেন্সি)", "Invoicing", "Documents"] },
    compliance: ["tds", "vat", "duty"],
    articles: ["0070-odoo-freight-forwarding-cf-agents-bangladesh", "0019-hs-code-customs-odoo-bangladesh", "0071-ait-income-tax-withholding-odoo-bangladesh"],
    tools: ["import-duty-calculator", "vat-mushak-helper"]
  },
  {
    slug: "hospital-diagnostic", est: "services", tag: "Healthcare", tagBn: "স্বাস্থ্যসেবা",
    en: { name: "Hospitals & Diagnostic Centres", short: "Patient billing, pharmacy stock, reagents, doctor commissions and referrals.",
      pains: ["Billing across OPD, IPD, tests and pharmacy", "Reagent and consumable stock with expiry", "Doctor fees, commissions and referral payouts", "Equipment maintenance and calibration"],
      modules: ["Invoicing / POS", "Inventory (expiry)", "Accounting", "Maintenance", "HR & Payroll"] },
    bn: { name: "হাসপাতাল ও ডায়াগনস্টিক সেন্টার", short: "রোগীর বিলিং, ফার্মেসির স্টক, রিএজেন্ট, ডাক্তারের কমিশন আর রেফারেল।",
      pains: ["OPD, IPD, টেস্ট আর ফার্মেসি জুড়ে বিলিং", "মেয়াদসহ রিএজেন্ট আর কনজিউমেবলের স্টক", "ডাক্তারের ফি, কমিশন আর রেফারেলের পেমেন্ট", "যন্ত্রপাতির মেইনটেন্যান্স আর ক্যালিব্রেশন"],
      modules: ["Invoicing / POS", "Inventory (মেয়াদ)", "Accounting", "Maintenance", "HR ও Payroll"] },
    compliance: ["vat", "tds", "data"],
    articles: ["0089-odoo-hospital-diagnostic-center-bangladesh", "0078-bangladesh-data-protection-act-cloud-erp"],
    tools: ["vat-mushak-helper", "odoo-cost-estimator"]
  },
  {
    slug: "real-estate", est: "services", tag: "Property", tagBn: "আবাসন",
    en: { name: "Real Estate Developers", short: "Flat/plot bookings, instalment schedules, construction costs by project.",
      pains: ["Booking, allotment and instalment schedules per flat or plot", "Construction cost per project, with material issued to sites", "Land owner shares and handover", "Registration costs and VAT on construction services"],
      modules: ["Sales + subscriptions / instalments", "Project (cost by site)", "Purchase", "Inventory (site stores)", "Accounting"] },
    bn: { name: "রিয়েল এস্টেট ডেভেলপার", short: "ফ্ল্যাট/প্লট বুকিং, কিস্তির সময়সূচি, প্রজেক্টভিত্তিক নির্মাণ খরচ।",
      pains: ["প্রতিটি ফ্ল্যাট বা প্লটের বুকিং, বরাদ্দ আর কিস্তির সময়সূচি", "প্রজেক্টভিত্তিক নির্মাণ খরচ, সাইটে পাঠানো ম্যাটেরিয়ালসহ", "জমির মালিকের অংশ আর হস্তান্তর", "রেজিস্ট্রেশন খরচ আর নির্মাণ সেবায় VAT"],
      modules: ["Sales ও কিস্তি", "Project (সাইটভিত্তিক খরচ)", "Purchase", "Inventory (সাইট স্টোর)", "Accounting"] },
    compliance: ["vat", "tds"],
    articles: ["0090-odoo-real-estate-developers-bangladesh", "0098-odoo-consolidation-group-companies-bangladesh"],
    tools: ["vat-mushak-helper", "odoo-cost-estimator"]
  },
  {
    slug: "restaurants-qsr", est: "services", tag: "Food service", tagBn: "খাদ্যসেবা",
    en: { name: "Restaurants & QSR Chains", short: "Outlet POS, central kitchen, recipe costing and VAT on food service.",
      pains: ["POS across outlets with delivery-platform orders", "Central kitchen production and transfers to outlets", "Recipe costing and wastage", "VAT on restaurant services, and online-sale VAT guidelines"],
      modules: ["Point of Sale", "Manufacturing (central kitchen)", "Inventory", "Purchase", "Accounting"] },
    bn: { name: "রেস্টুরেন্ট ও QSR চেইন", short: "আউটলেটের POS, সেন্ট্রাল কিচেন, রেসিপি কস্টিং আর খাদ্যসেবায় VAT।",
      pains: ["ডেলিভারি প্ল্যাটফর্মের অর্ডারসহ সব আউটলেটের POS", "সেন্ট্রাল কিচেনের উৎপাদন আর আউটলেটে ট্রান্সফার", "রেসিপি কস্টিং আর অপচয়", "রেস্টুরেন্ট সেবায় VAT, আর অনলাইন বিক্রির VAT নির্দেশিকা"],
      modules: ["Point of Sale", "Manufacturing (সেন্ট্রাল কিচেন)", "Inventory", "Purchase", "Accounting"] },
    compliance: ["vat"],
    articles: ["0091-odoo-restaurant-qsr-chains-bangladesh", "0064-odoo-pos-retail-chains-bangladesh"],
    tools: ["vat-mushak-helper", "odoo-cost-estimator"]
  },
  {
    slug: "retail-ecommerce", est: "services", tag: "Retail", tagBn: "রিটেইল",
    en: { name: "Retail Chains & E-commerce", short: "Multi-outlet POS, loyalty, online marketplace orders and the new online-sale VAT rules.",
      pains: ["Stock across outlets and the online store in one place", "Promotions, loyalty and returns", "Marketplace orders and courier cash-on-delivery reconciliation", "VAT guidelines for online retail vs marketplace commission"],
      modules: ["Point of Sale", "eCommerce", "Inventory", "Sales", "Accounting"] },
    bn: { name: "রিটেইল চেইন ও ই-কমার্স", short: "একাধিক আউটলেটের POS, লয়্যালটি, অনলাইন মার্কেটপ্লেসের অর্ডার আর অনলাইন বিক্রির নতুন VAT নিয়ম।",
      pains: ["আউটলেট আর অনলাইন স্টোরের স্টক এক জায়গায়", "প্রমোশন, লয়্যালটি আর রিটার্ন", "মার্কেটপ্লেসের অর্ডার আর কুরিয়ারের ক্যাশ-অন-ডেলিভারি মেলানো", "অনলাইন রিটেইল আর মার্কেটপ্লেস কমিশনের VAT নির্দেশিকা"],
      modules: ["Point of Sale", "eCommerce", "Inventory", "Sales", "Accounting"] },
    compliance: ["vat", "data"],
    articles: ["0064-odoo-pos-retail-chains-bangladesh", "0059-odoo-ecommerce-integration-bangladesh", "0065-odoo-barcode-warehouse-scanning-bangladesh"],
    tools: ["vat-mushak-helper", "odoo-cost-estimator"]
  },
  {
    slug: "it-professional-services", est: "services", tag: "Services", tagBn: "সেবা",
    en: { name: "IT & Professional Services", short: "Timesheets, project billing, imported software VAT and startup exemptions.",
      pains: ["Billable hours and project profitability", "Foreign software and SaaS subscriptions (VAT now withheld by the bank)", "Export of services and inward-remittance tax (now 5%)", "Startup VAT exemption until 2035, conditional on ERP records"],
      modules: ["Project", "Timesheets", "Helpdesk", "Invoicing", "Accounting"] },
    bn: { name: "IT ও প্রফেশনাল সার্ভিস", short: "টাইমশিট, প্রজেক্ট বিলিং, আমদানিকৃত সফটওয়্যারের VAT আর স্টার্টআপের অব্যাহতি।",
      pains: ["বিলযোগ্য ঘণ্টা আর প্রজেক্টের লাভ", "বিদেশি সফটওয়্যার আর SaaS সাবস্ক্রিপশন (VAT এখন ব্যাংক কেটে রাখে)", "সেবা রপ্তানি আর বিদেশ থেকে আসা আয়ে কর (এখন ৫%)", "২০৩৫ পর্যন্ত স্টার্টআপের VAT অব্যাহতি, শর্ত ERP-তে রেকর্ড রাখা"],
      modules: ["Project", "Timesheets", "Helpdesk", "Invoicing", "Accounting"] },
    compliance: ["vat", "tds", "data"],
    articles: ["0092-odoo-it-professional-services-firms-bangladesh", "0094-odoo-timesheets-billable-hours-bangladesh", "0095-odoo-helpdesk-ticketing-setup-bangladesh"],
    tools: ["vat-mushak-helper", "odoo-cost-estimator"]
  }
];
