// Non-Lab pages included in the site search index (both languages).
module.exports = [
  { u: "/tools/odoo-cost-estimator/", k: "tool", en: { t: "Odoo Cost Estimator", d: "Odoo ERP cost in BDT and USD: licence, implementation, training and Bangladesh compliance, year 1–3 TCO." }, bn: { t: "Odoo কস্ট এস্টিমেটর", d: "BDT আর USD-এ Odoo ERP-র খরচ: লাইসেন্স, বাস্তবায়ন, ট্রেনিং আর বাংলাদেশের কমপ্লায়েন্স, ১–৩ বছরের TCO।" } },
  { u: "/tools/odoo-roi-calculator/", k: "tool", en: { t: "Odoo ROI Calculator", d: "3-year ROI and break-even month from labour, inventory, procurement, waste and collections benefits." }, bn: { t: "Odoo ROI ক্যালকুলেটর", d: "শ্রম, স্টক, ক্রয়, অপচয় আর আদায়ের লাভ থেকে ৩ বছরের ROI আর ব্রেক-ইভেনের মাস।" } },
  { u: "/tools/erp-readiness-assessment/", k: "tool", en: { t: "ERP Readiness Assessment", d: "25 questions: readiness score, red flags and next steps before an ERP project." }, bn: { t: "ERP প্রস্তুতি যাচাই", d: "২৫টি প্রশ্ন: ERP প্রজেক্টের আগে প্রস্তুতির স্কোর, লাল পতাকা আর পরের ধাপ।" } },
  { u: "/tools/odoo-quote-checker/", k: "tool", en: { t: "Odoo Quote Checker", d: "Check a vendor's implementation quote for missing items, hidden cost and fair price." }, bn: { t: "Odoo কোটেশন চেকার", d: "ভেন্ডরের বাস্তবায়ন কোটেশনে কী বাদ আছে, লুকানো খরচ কত, আর দাম ন্যায্য কি না যাচাই করুন।" } },
  { u: "/tools/rmg-wage-calculator/", k: "tool", en: { t: "RMG Wage Calculator", d: "Garment worker wages by grade, 9% increment, overtime, festival bonus and factory payroll." }, bn: { t: "RMG মজুরি ক্যালকুলেটর", d: "গ্রেড অনুযায়ী গার্মেন্টস শ্রমিকের মজুরি, ৯% ইনক্রিমেন্ট, ওভারটাইম, উৎসব বোনাস আর কারখানার পে-রোল।" } },
  { u: "/tools/import-duty-calculator/", k: "tool", en: { t: "Import Duty & Landed Cost Calculator", d: "CD, RD, SD, VAT, AIT and AT on imports, TTI and landed cost per unit." }, bn: { t: "আমদানি শুল্ক ও ল্যান্ডেড কস্ট ক্যালকুলেটর", d: "আমদানিতে CD, RD, SD, VAT, AIT আর AT, TTI আর প্রতি ইউনিটের ল্যান্ডেড কস্ট।" } },
  { u: "/tools/vat-mushak-helper/", k: "tool", en: { t: "VAT & Mushak Helper", d: "Which Mushak forms and VAT returns apply after the Finance Act 2026, plus a VAT/SD/VDS calculator." }, bn: { t: "VAT ও মূসক হেল্পার", d: "অর্থ আইন ২০২৬-এর পর কোন মূসক ফর্ম আর VAT রিটার্ন প্রযোজ্য, সঙ্গে VAT/SD/VDS ক্যালকুলেটর।" } },
  { u: "/benchmarks/odoo-implementation-pricing-bangladesh/", k: "guide", en: { t: "What a fair Odoo quote looks like — price benchmarks", d: "Odoo implementation price ranges in Bangladesh by size, industry and line item." }, bn: { t: "ন্যায্য Odoo কোটেশন দেখতে কেমন: দামের মানদণ্ড", d: "আকার, ইন্ডাস্ট্রি আর প্রতিটি খাত অনুযায়ী বাংলাদেশে Odoo বাস্তবায়নের দামের পরিসর।" } },
  { u: "/compliance-watch/", k: "guide", en: { t: "Compliance Watch — VAT, customs, tax & wage changes", d: "Finance Act 2026 quarterly VAT returns, Mushak 9.1.1, withholding changes, RMG wages and what to change in Odoo." }, bn: { t: "কমপ্লায়েন্স ওয়াচ: VAT, কাস্টমস, কর ও মজুরির পরিবর্তন", d: "অর্থ আইন ২০২৬-এর ত্রৈমাসিক VAT রিটার্ন, মূসক ৯.১.১, উৎসে করের পরিবর্তন, RMG মজুরি আর Odoo-তে কী বদলাতে হবে।" } },
  { u: "/glossary/", k: "guide", en: { t: "ERP & compliance glossary (English + Bangla)", d: "500+ ERP, accounting, VAT, customs, manufacturing and HR terms explained." }, bn: { t: "ERP ও কমপ্লায়েন্স শব্দকোষ (ইংরেজি + বাংলা)", d: "৫০০+ ERP, হিসাব, VAT, কাস্টমস, উৎপাদন আর HR-এর শব্দের ব্যাখ্যা।" } },
  { u: "/resources/", k: "guide", en: { t: "ERP project templates (Excel & Word downloads)", d: "RFP, project charter, UAT scripts, data migration and training plan templates." }, bn: { t: "ERP প্রজেক্টের টেমপ্লেট (Excel ও Word ডাউনলোড)", d: "RFP, প্রজেক্ট চার্টার, UAT স্ক্রিপ্ট, ডেটা মাইগ্রেশন আর ট্রেনিং প্ল্যানের টেমপ্লেট।" } },
  { u: "/courses/01-requirements-gathering/", k: "course", en: { t: "Course 01 — Requirements gathering for ERP", d: "Free 9-lesson course on discovery, workshops and requirements documents." }, bn: { t: "কোর্স ০১: ERP-র জন্য রিকোয়ারমেন্ট সংগ্রহ", d: "ডিসকভারি, ওয়ার্কশপ আর রিকোয়ারমেন্ট ডকুমেন্ট নিয়ে ৯ লেসনের বিনামূল্যের কোর্স।" } },
  { u: "/courses/02-uat-go-live/", k: "course", en: { t: "Course 02 — UAT, cut-over & go-live", d: "Free course on testing, data cut-over, go/no-go decisions and hypercare." }, bn: { t: "কোর্স ০২: UAT, কাট-ওভার ও গো-লাইভ", d: "টেস্টিং, ডেটা কাট-ওভার, go/no-go সিদ্ধান্ত আর হাইপারকেয়ার নিয়ে বিনামূল্যের কোর্স।" } },
  { u: "/services/odoo-partner-consultant/", k: "service", en: { t: "Odoo consulting services", d: "Independent Odoo functional consulting for Bangladeshi companies." }, bn: { t: "Odoo কনসাল্টিং সেবা", d: "বাংলাদেশি কোম্পানির জন্য স্বাধীন Odoo ফাংশনাল কনসাল্টিং।" } },
  { u: "/services/manufacturing-erp-consultant/", k: "service", en: { t: "Manufacturing ERP consultant", d: "ERP consulting for Bangladeshi manufacturers: RMG, textile, pharma and more." }, bn: { t: "ম্যানুফ্যাকচারিং ERP কনসালট্যান্ট", d: "বাংলাদেশের উৎপাদকদের জন্য ERP কনসাল্টিং: RMG, টেক্সটাইল, ফার্মা আর আরও।" } }
];
